/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.lpp.LPP_PDU_Definitions;

import com.objsys.asn1j.runtime.*;

public class CommonIEsProvideAssistanceData extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_LPP_PDU_DefinitionsRtkey._rtkey);
      Asn1Type._setLicLocation(_LPP_PDU_DefinitionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "CommonIEsProvideAssistanceData";
   }

   protected SegmentationInfo_r14 segmentationInfo_r14 = null;  // optional
   protected PeriodicAssistanceDataControlParameters_r15 periodicAssistanceData_r15;  // optional
   protected Asn1OpenExt extElem1;

   public CommonIEsProvideAssistanceData () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public CommonIEsProvideAssistanceData (
      SegmentationInfo_r14 segmentationInfo_r14_,
      PeriodicAssistanceDataControlParameters_r15 periodicAssistanceData_r15_
   ) {
      super();
      setSegmentationInfo_r14 (segmentationInfo_r14_);
      setPeriodicAssistanceData_r15 (periodicAssistanceData_r15_);
   }

   public void init () {
      segmentationInfo_r14 = null;
      periodicAssistanceData_r15 = null;
      extElem1 = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof CommonIEsProvideAssistanceData) ) return false;

      CommonIEsProvideAssistanceData rhs = (CommonIEsProvideAssistanceData) obj;

      if (segmentationInfo_r14 == null) {
         if (rhs.segmentationInfo_r14 != null) return false;
      }
      else {
         if (!segmentationInfo_r14.equals(rhs.segmentationInfo_r14)) {
            return false;
         }
      }

      if (periodicAssistanceData_r15 == null) {
         if (rhs.periodicAssistanceData_r15 != null) return false;
      }
      else {
         if (!periodicAssistanceData_r15.equals(rhs.periodicAssistanceData_r15)) {
            return false;
         }
      }

      if (extElem1 == null) {
         if (rhs.extElem1 != null) return false;
      }
      else {
         if (!extElem1.equals(rhs.extElem1)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (segmentationInfo_r14 != null) __code = 31*__code + segmentationInfo_r14.hashCode();
      if (periodicAssistanceData_r15 != null) __code = 31*__code + periodicAssistanceData_r15.hashCode();
      if (extElem1 != null) __code = 31*__code + extElem1.hashCode();

      return __code;
   }

   /**
    * Accessor/mutator methods for SegmentationInfo_r14
    */
   public SegmentationInfo_r14 getSegmentationInfo_r14 () {
      return segmentationInfo_r14;
   }

   public void setSegmentationInfo_r14 (SegmentationInfo_r14 value) {
      this.segmentationInfo_r14 = value;
   }

   public boolean hasSegmentationInfo_r14 () {
      return (segmentationInfo_r14 != null);
   }

   /**
    * Accessor/mutator methods for PeriodicAssistanceData_r15
    */
   public PeriodicAssistanceDataControlParameters_r15 getPeriodicAssistanceData_r15 () {
      return periodicAssistanceData_r15;
   }

   public void setPeriodicAssistanceData_r15 (PeriodicAssistanceDataControlParameters_r15 value) {
      this.periodicAssistanceData_r15 = value;
   }

   public boolean hasPeriodicAssistanceData_r15 () {
      return (periodicAssistanceData_r15 != null);
   }

   /**
    * Accessor/mutator methods for ExtElem1
    */
   public Asn1OpenExt getExtElem1 () {
      return extElem1;
   }

   public void setExtElem1 (Asn1OpenExt value) {
      this.extElem1 = value;
   }

   public int getElementCount() { return 3; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return segmentationInfo_r14;
         case 1: return periodicAssistanceData_r15;
         case 2: return extElem1;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "segmentationInfo-r14";
         case 1: return "periodicAssistanceData-r15";
         case 2: return null;
         default: return null;
      }
   }


   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      init ();

      // extension bit

      boolean extbit = buffer.decodeBit ("extbit");

      // optional bits

      if (extbit) {

         int bitcnt = buffer.decodeSmallLength(), i = 0;
         long bitidx = buffer.getBitOffset() + bitcnt;
         boolean[] bitmap = new boolean [bitcnt];

         if (i < bitcnt) bitmap[i++] = buffer.decodeBit ("segmentationInfo_r14Present");
         if (i < bitcnt) bitmap[i++] = buffer.decodeBit ("periodicAssistanceData_r15Present");

         while (i < bitcnt) {
            bitmap[i++] = buffer.decodeBit ("unknown");
         }

         i = 0;

         // decode segmentationInfo_r14

         if (i < bitcnt && bitmap[i++]) {
            buffer.getContext().eventDispatcher.startElement("segmentationInfo_r14", -1);

            long _curidx = buffer.getBitOffset();
            bitidx = buffer.decodeExtLength ();
            if (bitidx - _curidx >= 131088)  {
               throw new Asn1Exception ("PER fragmentation not enabled: add -perindef to decode");
            }

            {
               int tval = SegmentationInfo_r14.decodeEnumValue (buffer);
               segmentationInfo_r14 = SegmentationInfo_r14.valueOf (tval);
               buffer.moveBitCursor (bitidx);
            }
            buffer.getContext().eventDispatcher.endElement("segmentationInfo_r14", -1);

         }
         else {
            segmentationInfo_r14 = null;
         }

         // decode periodicAssistanceData_r15

         if (i < bitcnt && bitmap[i++]) {
            buffer.getContext().eventDispatcher.startElement("periodicAssistanceData_r15", -1);

            long _curidx = buffer.getBitOffset();
            bitidx = buffer.decodeExtLength ();
            if (bitidx - _curidx >= 131088)  {
               throw new Asn1Exception ("PER fragmentation not enabled: add -perindef to decode");
            }

            periodicAssistanceData_r15 = new PeriodicAssistanceDataControlParameters_r15();
            periodicAssistanceData_r15.decode (buffer);

            buffer.moveBitCursor (bitidx);
            buffer.getContext().eventDispatcher.endElement("periodicAssistanceData_r15", -1);

         }
         else {
            periodicAssistanceData_r15 = null;
         }

         // decode unknown extension elements

         if (i < bitcnt) {
            Asn1OpenType openType = null;
            extElem1 = new Asn1OpenExt();
            int j = 0;
            while (i < bitcnt) {
               if (bitmap[i]) {
                  buffer.getContext().eventDispatcher.startElement("...", -1);

                  openType = extElem1.decodeOpenType (buffer, true, j++);
               }
               else {
                  extElem1.setOpenType (null, j++);
               }
               i++;
            }
         }
         buffer.byteAlign ();

      }

   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      // extension bit

      boolean extbit = ((segmentationInfo_r14 != null) ||
      (periodicAssistanceData_r15 != null) ||
      ((extElem1 != null) && (!extElem1.value.isEmpty()))
      );

      buffer.encodeBit (extbit, "extbit");

      if (extbit) {

         // encode extension optional bits length

         int bitcnt = 2;
         if (extElem1 != null) bitcnt += extElem1.value.size();
         buffer.encodeSmallLength (bitcnt);

         // encode optional bits

         buffer.encodeBit ((segmentationInfo_r14 != null), null);
         buffer.encodeBit ((periodicAssistanceData_r15 != null), null);

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encodeExtBits (buffer);
         }

         // encode extension elements

         Asn1PerEncodeBuffer mainBuffer = buffer;
         buffer = new Asn1PerEncodeBuffer (buffer.isAligned());

         // segmentationInfo_r14

         if (segmentationInfo_r14 != null) {
            buffer.reset();
            segmentationInfo_r14.encode (buffer);
            buffer.getContext().eventDispatcher.startElement("segmentationInfo_r14", -1);

            mainBuffer.encodeOpenType (buffer, null);

            buffer.getContext().eventDispatcher.endElement("segmentationInfo_r14", -1);
         }

         // periodicAssistanceData_r15

         if (periodicAssistanceData_r15 != null) {
            buffer.reset();
            periodicAssistanceData_r15.encode (buffer);
            buffer.getContext().eventDispatcher.startElement("periodicAssistanceData_r15", -1);

            mainBuffer.encodeOpenType (buffer, null);

            buffer.getContext().eventDispatcher.endElement("periodicAssistanceData_r15", -1);
         }

         buffer = mainBuffer;

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encode (buffer);
         }
      }
   }

}
