/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.lpp.LPP_PDU_Definitions;

import com.objsys.asn1j.runtime.*;

public class DL_PRS_ResourcesCapabilityPerBand_r16 extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_LPP_PDU_DefinitionsRtkey._rtkey);
      Asn1Type._setLicLocation(_LPP_PDU_DefinitionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "DL-PRS-ResourcesCapabilityPerBand-r16";
   }

   protected FreqBandIndicatorNR_r16 freqBandIndicatorNR_r16;
   protected DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerResourceSet_r16 maxNrOfDL_PRS_ResourcesPerResourceSet_r16 = null;
   protected DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 = null;
   protected Asn1OpenExt extElem1;

   public DL_PRS_ResourcesCapabilityPerBand_r16 () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public DL_PRS_ResourcesCapabilityPerBand_r16 (
      FreqBandIndicatorNR_r16 freqBandIndicatorNR_r16_,
      DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerResourceSet_r16 maxNrOfDL_PRS_ResourcesPerResourceSet_r16_,
      DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16_
   ) throws Asn1Exception {
      super();
      setFreqBandIndicatorNR_r16 (freqBandIndicatorNR_r16_);
      setMaxNrOfDL_PRS_ResourcesPerResourceSet_r16 (maxNrOfDL_PRS_ResourcesPerResourceSet_r16_);
      setMaxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 (maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16_);
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public DL_PRS_ResourcesCapabilityPerBand_r16 (long freqBandIndicatorNR_r16_,
      DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerResourceSet_r16 maxNrOfDL_PRS_ResourcesPerResourceSet_r16_,
      DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16_
   ) throws Asn1Exception {
      super();
      setFreqBandIndicatorNR_r16 (freqBandIndicatorNR_r16_);
      setMaxNrOfDL_PRS_ResourcesPerResourceSet_r16 (maxNrOfDL_PRS_ResourcesPerResourceSet_r16_);
      setMaxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 (maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16_);
   }

   public void init () {
      freqBandIndicatorNR_r16 = null;
      maxNrOfDL_PRS_ResourcesPerResourceSet_r16 = null;
      maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 = null;
      extElem1 = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof DL_PRS_ResourcesCapabilityPerBand_r16) ) return false;

      DL_PRS_ResourcesCapabilityPerBand_r16 rhs = (DL_PRS_ResourcesCapabilityPerBand_r16) obj;

      if (freqBandIndicatorNR_r16 == null) {
         if (rhs.freqBandIndicatorNR_r16 != null) return false;
      }
      else {
         if (!freqBandIndicatorNR_r16.equals(rhs.freqBandIndicatorNR_r16)) {
            return false;
         }
      }

      if (maxNrOfDL_PRS_ResourcesPerResourceSet_r16 == null) {
         if (rhs.maxNrOfDL_PRS_ResourcesPerResourceSet_r16 != null) return false;
      }
      else {
         if (!maxNrOfDL_PRS_ResourcesPerResourceSet_r16.equals(rhs.maxNrOfDL_PRS_ResourcesPerResourceSet_r16)) {
            return false;
         }
      }

      if (maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 == null) {
         if (rhs.maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 != null) return false;
      }
      else {
         if (!maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16.equals(rhs.maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16)) {
            return false;
         }
      }

      if (extElem1 == null) {
         if (rhs.extElem1 != null) return false;
      }
      else {
         if (!extElem1.equals(rhs.extElem1)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (freqBandIndicatorNR_r16 != null) __code = 31*__code + freqBandIndicatorNR_r16.hashCode();
      if (maxNrOfDL_PRS_ResourcesPerResourceSet_r16 != null) __code = 31*__code + maxNrOfDL_PRS_ResourcesPerResourceSet_r16.hashCode();
      if (maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 != null) __code = 31*__code + maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16.hashCode();
      if (extElem1 != null) __code = 31*__code + extElem1.hashCode();

      return __code;
   }

   /**
    * Accessor/mutator methods for FreqBandIndicatorNR_r16
    */
   public FreqBandIndicatorNR_r16 getFreqBandIndicatorNR_r16 () {
      return freqBandIndicatorNR_r16;
   }

   public void setFreqBandIndicatorNR_r16 (FreqBandIndicatorNR_r16 value) 
      throws Asn1Exception
   {
      if (!((value.value >= 1 && value.value <= 1024))) {
         throw new Asn1ConsVioException ("value.value", value.value);
      }

      this.freqBandIndicatorNR_r16 = value;
   }

   public void setFreqBandIndicatorNR_r16 (long value) 
      throws Asn1Exception
   {
      setFreqBandIndicatorNR_r16 (new FreqBandIndicatorNR_r16(value));
   }

   /**
    * Accessor/mutator methods for MaxNrOfDL_PRS_ResourcesPerResourceSet_r16
    */
   public DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerResourceSet_r16 getMaxNrOfDL_PRS_ResourcesPerResourceSet_r16 () {
      return maxNrOfDL_PRS_ResourcesPerResourceSet_r16;
   }

   public void setMaxNrOfDL_PRS_ResourcesPerResourceSet_r16 (DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerResourceSet_r16 value) {
      this.maxNrOfDL_PRS_ResourcesPerResourceSet_r16 = value;
   }

   /**
    * Accessor/mutator methods for MaxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16
    */
   public DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 getMaxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 () {
      return maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16;
   }

   public void setMaxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 (DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 value) {
      this.maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 = value;
   }

   /**
    * Accessor/mutator methods for ExtElem1
    */
   public Asn1OpenExt getExtElem1 () {
      return extElem1;
   }

   public void setExtElem1 (Asn1OpenExt value) {
      this.extElem1 = value;
   }

   public int getElementCount() { return 4; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return freqBandIndicatorNR_r16;
         case 1: return maxNrOfDL_PRS_ResourcesPerResourceSet_r16;
         case 2: return maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16;
         case 3: return extElem1;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "freqBandIndicatorNR-r16";
         case 1: return "maxNrOfDL-PRS-ResourcesPerResourceSet-r16";
         case 2: return "maxNrOfDL-PRS-ResourcesPerPositioningFrequencylayer-r16";
         case 3: return null;
         default: return null;
      }
   }


   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      init ();

      // extension bit

      boolean extbit = buffer.decodeBit ("extbit");

      // decode freqBandIndicatorNR_r16

      buffer.getContext().eventDispatcher.startElement("freqBandIndicatorNR_r16", -1);

      freqBandIndicatorNR_r16 = new FreqBandIndicatorNR_r16();
      freqBandIndicatorNR_r16.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("freqBandIndicatorNR_r16", -1);

      // decode maxNrOfDL_PRS_ResourcesPerResourceSet_r16

      buffer.getContext().eventDispatcher.startElement("maxNrOfDL_PRS_ResourcesPerResourceSet_r16", -1);

      {
         int tval = DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerResourceSet_r16.decodeEnumValue (buffer);
         maxNrOfDL_PRS_ResourcesPerResourceSet_r16 = DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerResourceSet_r16.valueOf (tval);
      }
      buffer.getContext().eventDispatcher.endElement("maxNrOfDL_PRS_ResourcesPerResourceSet_r16", -1);

      // decode maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16

      buffer.getContext().eventDispatcher.startElement("maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16", -1);

      {
         int tval = DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16.decodeEnumValue (buffer);
         maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 = DL_PRS_ResourcesCapabilityPerBand_r16_maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16.valueOf (tval);
      }
      buffer.getContext().eventDispatcher.endElement("maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16", -1);

      if (extbit) {

         int bitcnt = buffer.decodeSmallLength(), i = 0;
         long bitidx = buffer.getBitOffset() + bitcnt;
         boolean[] bitmap = new boolean [bitcnt];

         while (i < bitcnt) {
            bitmap[i++] = buffer.decodeBit ("unknown");
         }

         i = 0;

         // decode unknown extension elements

         if (i < bitcnt) {
            Asn1OpenType openType = null;
            extElem1 = new Asn1OpenExt();
            int j = 0;
            while (i < bitcnt) {
               if (bitmap[i]) {
                  buffer.getContext().eventDispatcher.startElement("...", -1);

                  openType = extElem1.decodeOpenType (buffer, true, j++);
               }
               else {
                  extElem1.setOpenType (null, j++);
               }
               i++;
            }
         }
         buffer.byteAlign ();

      }

   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      // extension bit

      boolean extbit = (((extElem1 != null) && (!extElem1.value.isEmpty()))
      );

      buffer.encodeBit (extbit, "extbit");

      // encode freqBandIndicatorNR_r16

      if (freqBandIndicatorNR_r16 != null) {
         buffer.getContext().eventDispatcher.startElement("freqBandIndicatorNR_r16", -1);

         freqBandIndicatorNR_r16.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("freqBandIndicatorNR_r16", -1);
      }
      else throw new Asn1MissingRequiredException ("freqBandIndicatorNR_r16");

      // encode maxNrOfDL_PRS_ResourcesPerResourceSet_r16

      if (maxNrOfDL_PRS_ResourcesPerResourceSet_r16 != null) {
         buffer.getContext().eventDispatcher.startElement("maxNrOfDL_PRS_ResourcesPerResourceSet_r16", -1);

         maxNrOfDL_PRS_ResourcesPerResourceSet_r16.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("maxNrOfDL_PRS_ResourcesPerResourceSet_r16", -1);
      }
      else throw new Asn1MissingRequiredException ("maxNrOfDL_PRS_ResourcesPerResourceSet_r16");

      // encode maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16

      if (maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16 != null) {
         buffer.getContext().eventDispatcher.startElement("maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16", -1);

         maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16", -1);
      }
      else throw new Asn1MissingRequiredException ("maxNrOfDL_PRS_ResourcesPerPositioningFrequencylayer_r16");

      if (extbit) {

         // encode extension optional bits length

         int bitcnt = 0;
         if (extElem1 != null) bitcnt += extElem1.value.size();
         buffer.encodeSmallLength (bitcnt);

         // encode optional bits

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encodeExtBits (buffer);
         }

         // encode extension elements

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encode (buffer);
         }
      }
   }

}
