/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.lpp.LPP_PDU_Definitions;

import com.objsys.asn1j.runtime.*;

public class DL_SelectedPRS_ResourceIndex_r16 extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_LPP_PDU_DefinitionsRtkey._rtkey);
      Asn1Type._setLicLocation(_LPP_PDU_DefinitionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "DL-SelectedPRS-ResourceIndex-r16";
   }

   protected Asn1Integer nr_DL_SelectedPRS_ResourceIdIndex_r16;
   protected Asn1OpenExt extElem1;

   public DL_SelectedPRS_ResourceIndex_r16 () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public DL_SelectedPRS_ResourceIndex_r16 (
      Asn1Integer nr_DL_SelectedPRS_ResourceIdIndex_r16_
   ) throws Asn1Exception {
      super();
      setNr_DL_SelectedPRS_ResourceIdIndex_r16 (nr_DL_SelectedPRS_ResourceIdIndex_r16_);
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public DL_SelectedPRS_ResourceIndex_r16 (long nr_DL_SelectedPRS_ResourceIdIndex_r16_
   ) throws Asn1Exception {
      super();
      setNr_DL_SelectedPRS_ResourceIdIndex_r16 (nr_DL_SelectedPRS_ResourceIdIndex_r16_);
   }

   public void init () {
      nr_DL_SelectedPRS_ResourceIdIndex_r16 = null;
      extElem1 = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof DL_SelectedPRS_ResourceIndex_r16) ) return false;

      DL_SelectedPRS_ResourceIndex_r16 rhs = (DL_SelectedPRS_ResourceIndex_r16) obj;

      if (nr_DL_SelectedPRS_ResourceIdIndex_r16 == null) {
         if (rhs.nr_DL_SelectedPRS_ResourceIdIndex_r16 != null) return false;
      }
      else {
         if (!nr_DL_SelectedPRS_ResourceIdIndex_r16.equals(rhs.nr_DL_SelectedPRS_ResourceIdIndex_r16)) {
            return false;
         }
      }

      if (extElem1 == null) {
         if (rhs.extElem1 != null) return false;
      }
      else {
         if (!extElem1.equals(rhs.extElem1)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (nr_DL_SelectedPRS_ResourceIdIndex_r16 != null) __code = 31*__code + nr_DL_SelectedPRS_ResourceIdIndex_r16.hashCode();
      if (extElem1 != null) __code = 31*__code + extElem1.hashCode();

      return __code;
   }

   /**
    * Accessor/mutator methods for Nr_DL_SelectedPRS_ResourceIdIndex_r16
    */
   public Asn1Integer getNr_DL_SelectedPRS_ResourceIdIndex_r16 () {
      return nr_DL_SelectedPRS_ResourceIdIndex_r16;
   }

   public void setNr_DL_SelectedPRS_ResourceIdIndex_r16 (Asn1Integer value) 
      throws Asn1Exception
   {
      if (!((value.value >= 0 && value.value <= 63))) {
         throw new Asn1ConsVioException ("value.value", value.value);
      }

      this.nr_DL_SelectedPRS_ResourceIdIndex_r16 = value;
   }

   public void setNr_DL_SelectedPRS_ResourceIdIndex_r16 (long value) 
      throws Asn1Exception
   {
      setNr_DL_SelectedPRS_ResourceIdIndex_r16 (new Asn1Integer(value));
   }

   /**
    * Accessor/mutator methods for ExtElem1
    */
   public Asn1OpenExt getExtElem1 () {
      return extElem1;
   }

   public void setExtElem1 (Asn1OpenExt value) {
      this.extElem1 = value;
   }

   public int getElementCount() { return 2; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return nr_DL_SelectedPRS_ResourceIdIndex_r16;
         case 1: return extElem1;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "nr-DL-SelectedPRS-ResourceIdIndex-r16";
         case 1: return null;
         default: return null;
      }
   }


   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      init ();

      // extension bit

      boolean extbit = buffer.decodeBit ("extbit");

      // decode nr_DL_SelectedPRS_ResourceIdIndex_r16

      buffer.getContext().eventDispatcher.startElement("nr_DL_SelectedPRS_ResourceIdIndex_r16", -1);

      nr_DL_SelectedPRS_ResourceIdIndex_r16 = new Asn1Integer();
      nr_DL_SelectedPRS_ResourceIdIndex_r16.decode (buffer, 0, 63);
      buffer.getContext().eventDispatcher.endElement("nr_DL_SelectedPRS_ResourceIdIndex_r16", -1);

      if (extbit) {

         int bitcnt = buffer.decodeSmallLength(), i = 0;
         long bitidx = buffer.getBitOffset() + bitcnt;
         boolean[] bitmap = new boolean [bitcnt];

         while (i < bitcnt) {
            bitmap[i++] = buffer.decodeBit ("unknown");
         }

         i = 0;

         // decode unknown extension elements

         if (i < bitcnt) {
            Asn1OpenType openType = null;
            extElem1 = new Asn1OpenExt();
            int j = 0;
            while (i < bitcnt) {
               if (bitmap[i]) {
                  buffer.getContext().eventDispatcher.startElement("...", -1);

                  openType = extElem1.decodeOpenType (buffer, true, j++);
               }
               else {
                  extElem1.setOpenType (null, j++);
               }
               i++;
            }
         }
         buffer.byteAlign ();

      }

   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      // extension bit

      boolean extbit = (((extElem1 != null) && (!extElem1.value.isEmpty()))
      );

      buffer.encodeBit (extbit, "extbit");

      // encode nr_DL_SelectedPRS_ResourceIdIndex_r16

      if (nr_DL_SelectedPRS_ResourceIdIndex_r16 != null) {
         buffer.getContext().eventDispatcher.startElement("nr_DL_SelectedPRS_ResourceIdIndex_r16", -1);

         nr_DL_SelectedPRS_ResourceIdIndex_r16.encode (buffer, 0, 63);

         buffer.getContext().eventDispatcher.endElement("nr_DL_SelectedPRS_ResourceIdIndex_r16", -1);
      }
      else throw new Asn1MissingRequiredException ("nr_DL_SelectedPRS_ResourceIdIndex_r16");

      if (extbit) {

         // encode extension optional bits length

         int bitcnt = 0;
         if (extElem1 != null) bitcnt += extElem1.value.size();
         buffer.encodeSmallLength (bitcnt);

         // encode optional bits

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encodeExtBits (buffer);
         }

         // encode extension elements

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encode (buffer);
         }
      }
   }

}
