/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.lpp.LPP_PDU_Definitions;

import com.objsys.asn1j.runtime.*;

public class GNSS_TimeModelElementReq extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_LPP_PDU_DefinitionsRtkey._rtkey);
      Asn1Type._setLicLocation(_LPP_PDU_DefinitionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "GNSS-TimeModelElementReq";
   }

   protected Asn1Integer gnss_TO_IDsReq;
   protected Asn1Boolean deltaTreq;
   protected Asn1OpenExt extElem1;

   public GNSS_TimeModelElementReq () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public GNSS_TimeModelElementReq (
      Asn1Integer gnss_TO_IDsReq_,
      Asn1Boolean deltaTreq_
   ) throws Asn1Exception {
      super();
      setGnss_TO_IDsReq (gnss_TO_IDsReq_);
      setDeltaTreq (deltaTreq_);
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public GNSS_TimeModelElementReq (long gnss_TO_IDsReq_,
      boolean deltaTreq_
   ) throws Asn1Exception {
      super();
      setGnss_TO_IDsReq (gnss_TO_IDsReq_);
      setDeltaTreq (deltaTreq_);
   }

   public void init () {
      gnss_TO_IDsReq = null;
      deltaTreq = null;
      extElem1 = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof GNSS_TimeModelElementReq) ) return false;

      GNSS_TimeModelElementReq rhs = (GNSS_TimeModelElementReq) obj;

      if (gnss_TO_IDsReq == null) {
         if (rhs.gnss_TO_IDsReq != null) return false;
      }
      else {
         if (!gnss_TO_IDsReq.equals(rhs.gnss_TO_IDsReq)) {
            return false;
         }
      }

      if (deltaTreq == null) {
         if (rhs.deltaTreq != null) return false;
      }
      else {
         if (!deltaTreq.equals(rhs.deltaTreq)) {
            return false;
         }
      }

      if (extElem1 == null) {
         if (rhs.extElem1 != null) return false;
      }
      else {
         if (!extElem1.equals(rhs.extElem1)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (gnss_TO_IDsReq != null) __code = 31*__code + gnss_TO_IDsReq.hashCode();
      if (deltaTreq != null) __code = 31*__code + deltaTreq.hashCode();
      if (extElem1 != null) __code = 31*__code + extElem1.hashCode();

      return __code;
   }

   /**
    * Accessor/mutator methods for Gnss_TO_IDsReq
    */
   public Asn1Integer getGnss_TO_IDsReq () {
      return gnss_TO_IDsReq;
   }

   public void setGnss_TO_IDsReq (Asn1Integer value) 
      throws Asn1Exception
   {
      if (!((value.value >= 1 && value.value <= 15))) {
         throw new Asn1ConsVioException ("value.value", value.value);
      }

      this.gnss_TO_IDsReq = value;
   }

   public void setGnss_TO_IDsReq (long value) 
      throws Asn1Exception
   {
      setGnss_TO_IDsReq (new Asn1Integer(value));
   }

   /**
    * Accessor/mutator methods for DeltaTreq
    */
   public Asn1Boolean getDeltaTreq () {
      return deltaTreq;
   }

   public void setDeltaTreq (Asn1Boolean value) {
      this.deltaTreq = value;
   }

   public void setDeltaTreq (boolean value) {
      setDeltaTreq (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for ExtElem1
    */
   public Asn1OpenExt getExtElem1 () {
      return extElem1;
   }

   public void setExtElem1 (Asn1OpenExt value) {
      this.extElem1 = value;
   }

   public int getElementCount() { return 3; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return gnss_TO_IDsReq;
         case 1: return deltaTreq;
         case 2: return extElem1;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "gnss-TO-IDsReq";
         case 1: return "deltaTreq";
         case 2: return null;
         default: return null;
      }
   }


   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      init ();

      // extension bit

      boolean extbit = buffer.decodeBit ("extbit");

      // decode gnss_TO_IDsReq

      buffer.getContext().eventDispatcher.startElement("gnss_TO_IDsReq", -1);

      gnss_TO_IDsReq = new Asn1Integer();
      gnss_TO_IDsReq.decode (buffer, 1, 15);
      buffer.getContext().eventDispatcher.endElement("gnss_TO_IDsReq", -1);

      // decode deltaTreq

      buffer.getContext().eventDispatcher.startElement("deltaTreq", -1);

      deltaTreq = new Asn1Boolean();
      deltaTreq.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("deltaTreq", -1);

      if (extbit) {

         int bitcnt = buffer.decodeSmallLength(), i = 0;
         long bitidx = buffer.getBitOffset() + bitcnt;
         boolean[] bitmap = new boolean [bitcnt];

         while (i < bitcnt) {
            bitmap[i++] = buffer.decodeBit ("unknown");
         }

         i = 0;

         // decode unknown extension elements

         if (i < bitcnt) {
            Asn1OpenType openType = null;
            extElem1 = new Asn1OpenExt();
            int j = 0;
            while (i < bitcnt) {
               if (bitmap[i]) {
                  buffer.getContext().eventDispatcher.startElement("...", -1);

                  openType = extElem1.decodeOpenType (buffer, true, j++);
               }
               else {
                  extElem1.setOpenType (null, j++);
               }
               i++;
            }
         }
         buffer.byteAlign ();

      }

   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      // extension bit

      boolean extbit = (((extElem1 != null) && (!extElem1.value.isEmpty()))
      );

      buffer.encodeBit (extbit, "extbit");

      // encode gnss_TO_IDsReq

      if (gnss_TO_IDsReq != null) {
         buffer.getContext().eventDispatcher.startElement("gnss_TO_IDsReq", -1);

         gnss_TO_IDsReq.encode (buffer, 1, 15);

         buffer.getContext().eventDispatcher.endElement("gnss_TO_IDsReq", -1);
      }
      else throw new Asn1MissingRequiredException ("gnss_TO_IDsReq");

      // encode deltaTreq

      if (deltaTreq != null) {
         buffer.getContext().eventDispatcher.startElement("deltaTreq", -1);

         deltaTreq.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("deltaTreq", -1);
      }
      else throw new Asn1MissingRequiredException ("deltaTreq");

      if (extbit) {

         // encode extension optional bits length

         int bitcnt = 0;
         if (extElem1 != null) bitcnt += extElem1.value.size();
         buffer.encodeSmallLength (bitcnt);

         // encode optional bits

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encodeExtBits (buffer);
         }

         // encode extension elements

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encode (buffer);
         }
      }
   }

}
