/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.lpp.LPP_PDU_Definitions;

import com.objsys.asn1j.runtime.*;

public class LPP_TransactionID extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_LPP_PDU_DefinitionsRtkey._rtkey);
      Asn1Type._setLicLocation(_LPP_PDU_DefinitionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "LPP-TransactionID";
   }

   protected Initiator initiator = null;
   protected TransactionNumber transactionNumber;
   protected Asn1OpenExt extElem1;

   public LPP_TransactionID () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public LPP_TransactionID (
      Initiator initiator_,
      TransactionNumber transactionNumber_
   ) throws Asn1Exception {
      super();
      setInitiator (initiator_);
      setTransactionNumber (transactionNumber_);
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public LPP_TransactionID (Initiator initiator_,
      long transactionNumber_
   ) throws Asn1Exception {
      super();
      setInitiator (initiator_);
      setTransactionNumber (transactionNumber_);
   }

   public void init () {
      initiator = null;
      transactionNumber = null;
      extElem1 = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof LPP_TransactionID) ) return false;

      LPP_TransactionID rhs = (LPP_TransactionID) obj;

      if (initiator == null) {
         if (rhs.initiator != null) return false;
      }
      else {
         if (!initiator.equals(rhs.initiator)) {
            return false;
         }
      }

      if (transactionNumber == null) {
         if (rhs.transactionNumber != null) return false;
      }
      else {
         if (!transactionNumber.equals(rhs.transactionNumber)) {
            return false;
         }
      }

      if (extElem1 == null) {
         if (rhs.extElem1 != null) return false;
      }
      else {
         if (!extElem1.equals(rhs.extElem1)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (initiator != null) __code = 31*__code + initiator.hashCode();
      if (transactionNumber != null) __code = 31*__code + transactionNumber.hashCode();
      if (extElem1 != null) __code = 31*__code + extElem1.hashCode();

      return __code;
   }

   /**
    * Accessor/mutator methods for Initiator
    */
   public Initiator getInitiator () {
      return initiator;
   }

   public void setInitiator (Initiator value) {
      this.initiator = value;
   }

   /**
    * Accessor/mutator methods for TransactionNumber
    */
   public TransactionNumber getTransactionNumber () {
      return transactionNumber;
   }

   public void setTransactionNumber (TransactionNumber value) 
      throws Asn1Exception
   {
      if (!((value.value >= 0 && value.value <= 255))) {
         throw new Asn1ConsVioException ("value.value", value.value);
      }

      this.transactionNumber = value;
   }

   public void setTransactionNumber (long value) 
      throws Asn1Exception
   {
      setTransactionNumber (new TransactionNumber(value));
   }

   /**
    * Accessor/mutator methods for ExtElem1
    */
   public Asn1OpenExt getExtElem1 () {
      return extElem1;
   }

   public void setExtElem1 (Asn1OpenExt value) {
      this.extElem1 = value;
   }

   public int getElementCount() { return 3; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return initiator;
         case 1: return transactionNumber;
         case 2: return extElem1;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "initiator";
         case 1: return "transactionNumber";
         case 2: return null;
         default: return null;
      }
   }


   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      init ();

      // extension bit

      boolean extbit = buffer.decodeBit ("extbit");

      // decode initiator

      buffer.getContext().eventDispatcher.startElement("initiator", -1);

      {
         int tval = Initiator.decodeEnumValue (buffer);
         initiator = Initiator.valueOf (tval);
      }
      buffer.getContext().eventDispatcher.endElement("initiator", -1);

      // decode transactionNumber

      buffer.getContext().eventDispatcher.startElement("transactionNumber", -1);

      transactionNumber = new TransactionNumber();
      transactionNumber.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("transactionNumber", -1);

      if (extbit) {

         int bitcnt = buffer.decodeSmallLength(), i = 0;
         long bitidx = buffer.getBitOffset() + bitcnt;
         boolean[] bitmap = new boolean [bitcnt];

         while (i < bitcnt) {
            bitmap[i++] = buffer.decodeBit ("unknown");
         }

         i = 0;

         // decode unknown extension elements

         if (i < bitcnt) {
            Asn1OpenType openType = null;
            extElem1 = new Asn1OpenExt();
            int j = 0;
            while (i < bitcnt) {
               if (bitmap[i]) {
                  buffer.getContext().eventDispatcher.startElement("...", -1);

                  openType = extElem1.decodeOpenType (buffer, true, j++);
               }
               else {
                  extElem1.setOpenType (null, j++);
               }
               i++;
            }
         }
         buffer.byteAlign ();

      }

   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      // extension bit

      boolean extbit = (((extElem1 != null) && (!extElem1.value.isEmpty()))
      );

      buffer.encodeBit (extbit, "extbit");

      // encode initiator

      if (initiator != null) {
         buffer.getContext().eventDispatcher.startElement("initiator", -1);

         initiator.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("initiator", -1);
      }
      else throw new Asn1MissingRequiredException ("initiator");

      // encode transactionNumber

      if (transactionNumber != null) {
         buffer.getContext().eventDispatcher.startElement("transactionNumber", -1);

         transactionNumber.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("transactionNumber", -1);
      }
      else throw new Asn1MissingRequiredException ("transactionNumber");

      if (extbit) {

         // encode extension optional bits length

         int bitcnt = 0;
         if (extElem1 != null) bitcnt += extElem1.value.size();
         buffer.encodeSmallLength (bitcnt);

         // encode optional bits

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encodeExtBits (buffer);
         }

         // encode extension elements

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encode (buffer);
         }
      }
   }

}
