/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.lpp.LPP_PDU_Definitions;

import com.objsys.asn1j.runtime.*;

public class NetworkTime_cellID_uTRA extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_LPP_PDU_DefinitionsRtkey._rtkey);
      Asn1Type._setLicLocation(_LPP_PDU_DefinitionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "SEQUENCE";
   }

   protected NetworkTime_cellID_uTRA_mode mode;
   protected CellGlobalIdEUTRA_AndUTRA cellGlobalIdUTRA;  // optional
   protected ARFCN_ValueUTRA uarfcn;
   protected Asn1OpenExt extElem1;

   public NetworkTime_cellID_uTRA () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public NetworkTime_cellID_uTRA (
      NetworkTime_cellID_uTRA_mode mode_,
      CellGlobalIdEUTRA_AndUTRA cellGlobalIdUTRA_,
      ARFCN_ValueUTRA uarfcn_
   ) throws Asn1Exception {
      super();
      setMode (mode_);
      setCellGlobalIdUTRA (cellGlobalIdUTRA_);
      setUarfcn (uarfcn_);
   }

   /**
    * This constructor is for required elements only.  It sets 
    * all elements to references to the given objects
    */
   public NetworkTime_cellID_uTRA (
      NetworkTime_cellID_uTRA_mode mode_,
      ARFCN_ValueUTRA uarfcn_
   ) throws Asn1Exception {
      super();
      setMode (mode_);
      setUarfcn (uarfcn_);
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public NetworkTime_cellID_uTRA (NetworkTime_cellID_uTRA_mode mode_,
      CellGlobalIdEUTRA_AndUTRA cellGlobalIdUTRA_,
      long uarfcn_
   ) throws Asn1Exception {
      super();
      setMode (mode_);
      setCellGlobalIdUTRA (cellGlobalIdUTRA_);
      setUarfcn (uarfcn_);
   }

   /**
    * This constructor is for required elements only.  It allows 
    * primitive data to be passed for all primitive elements.  
    * It will create new object wrappers for the primitive data 
    * and set other elements to references to the given objects. 
    */
   public NetworkTime_cellID_uTRA (
      NetworkTime_cellID_uTRA_mode mode_,
      long uarfcn_
   ) throws Asn1Exception {
      super();
      setMode (mode_);
      setUarfcn (uarfcn_);
   }

   public void init () {
      mode = null;
      cellGlobalIdUTRA = null;
      uarfcn = null;
      extElem1 = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof NetworkTime_cellID_uTRA) ) return false;

      NetworkTime_cellID_uTRA rhs = (NetworkTime_cellID_uTRA) obj;

      if (mode == null) {
         if (rhs.mode != null) return false;
      }
      else {
         if (!mode.equals(rhs.mode)) {
            return false;
         }
      }

      if (cellGlobalIdUTRA == null) {
         if (rhs.cellGlobalIdUTRA != null) return false;
      }
      else {
         if (!cellGlobalIdUTRA.equals(rhs.cellGlobalIdUTRA)) {
            return false;
         }
      }

      if (uarfcn == null) {
         if (rhs.uarfcn != null) return false;
      }
      else {
         if (!uarfcn.equals(rhs.uarfcn)) {
            return false;
         }
      }

      if (extElem1 == null) {
         if (rhs.extElem1 != null) return false;
      }
      else {
         if (!extElem1.equals(rhs.extElem1)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (mode != null) __code = 31*__code + mode.hashCode();
      if (cellGlobalIdUTRA != null) __code = 31*__code + cellGlobalIdUTRA.hashCode();
      if (uarfcn != null) __code = 31*__code + uarfcn.hashCode();
      if (extElem1 != null) __code = 31*__code + extElem1.hashCode();

      return __code;
   }

   /**
    * Accessor/mutator methods for Mode
    */
   public NetworkTime_cellID_uTRA_mode getMode () {
      return mode;
   }

   public void setMode (NetworkTime_cellID_uTRA_mode value) {
      this.mode = value;
   }

   /**
    * Accessor/mutator methods for CellGlobalIdUTRA
    */
   public CellGlobalIdEUTRA_AndUTRA getCellGlobalIdUTRA () {
      return cellGlobalIdUTRA;
   }

   public void setCellGlobalIdUTRA (CellGlobalIdEUTRA_AndUTRA value) {
      this.cellGlobalIdUTRA = value;
   }

   public boolean hasCellGlobalIdUTRA () {
      return (cellGlobalIdUTRA != null);
   }

   /**
    * Accessor/mutator methods for Uarfcn
    */
   public ARFCN_ValueUTRA getUarfcn () {
      return uarfcn;
   }

   public void setUarfcn (ARFCN_ValueUTRA value) 
      throws Asn1Exception
   {
      if (!((value.value >= 0 && value.value <= 16383))) {
         throw new Asn1ConsVioException ("value.value", value.value);
      }

      this.uarfcn = value;
   }

   public void setUarfcn (long value) 
      throws Asn1Exception
   {
      setUarfcn (new ARFCN_ValueUTRA(value));
   }

   /**
    * Accessor/mutator methods for ExtElem1
    */
   public Asn1OpenExt getExtElem1 () {
      return extElem1;
   }

   public void setExtElem1 (Asn1OpenExt value) {
      this.extElem1 = value;
   }

   public int getElementCount() { return 4; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return mode;
         case 1: return cellGlobalIdUTRA;
         case 2: return uarfcn;
         case 3: return extElem1;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "mode";
         case 1: return "cellGlobalIdUTRA";
         case 2: return "uarfcn";
         case 3: return null;
         default: return null;
      }
   }


   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      init ();

      // extension bit

      boolean extbit = buffer.decodeBit ("extbit");

      // optional bits

      boolean cellGlobalIdUTRAPresent = buffer.decodeBit ("cellGlobalIdUTRAPresent");

      // decode mode

      buffer.getContext().eventDispatcher.startElement("mode", -1);

      mode = new NetworkTime_cellID_uTRA_mode();
      mode.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("mode", -1);

      // decode cellGlobalIdUTRA

      if (cellGlobalIdUTRAPresent) {
         buffer.getContext().eventDispatcher.startElement("cellGlobalIdUTRA", -1);

         cellGlobalIdUTRA = new CellGlobalIdEUTRA_AndUTRA();
         cellGlobalIdUTRA.decode (buffer);
         buffer.getContext().eventDispatcher.endElement("cellGlobalIdUTRA", -1);
      }
      else {
         cellGlobalIdUTRA = null;
      }

      // decode uarfcn

      buffer.getContext().eventDispatcher.startElement("uarfcn", -1);

      uarfcn = new ARFCN_ValueUTRA();
      uarfcn.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("uarfcn", -1);

      if (extbit) {

         int bitcnt = buffer.decodeSmallLength(), i = 0;
         long bitidx = buffer.getBitOffset() + bitcnt;
         boolean[] bitmap = new boolean [bitcnt];

         while (i < bitcnt) {
            bitmap[i++] = buffer.decodeBit ("unknown");
         }

         i = 0;

         // decode unknown extension elements

         if (i < bitcnt) {
            Asn1OpenType openType = null;
            extElem1 = new Asn1OpenExt();
            int j = 0;
            while (i < bitcnt) {
               if (bitmap[i]) {
                  buffer.getContext().eventDispatcher.startElement("...", -1);

                  openType = extElem1.decodeOpenType (buffer, true, j++);
               }
               else {
                  extElem1.setOpenType (null, j++);
               }
               i++;
            }
         }
         buffer.byteAlign ();

      }

   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      // extension bit

      boolean extbit = (((extElem1 != null) && (!extElem1.value.isEmpty()))
      );

      buffer.encodeBit (extbit, "extbit");

      // encode optional elements bit mask

      buffer.encodeBit ((cellGlobalIdUTRA != null), null);

      // encode mode

      if (mode != null) {
         buffer.getContext().eventDispatcher.startElement("mode", -1);

         mode.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("mode", -1);
      }
      else throw new Asn1MissingRequiredException ("mode");

      // encode cellGlobalIdUTRA

      if (cellGlobalIdUTRA != null) {
         buffer.getContext().eventDispatcher.startElement("cellGlobalIdUTRA", -1);

         cellGlobalIdUTRA.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("cellGlobalIdUTRA", -1);
      }

      // encode uarfcn

      if (uarfcn != null) {
         buffer.getContext().eventDispatcher.startElement("uarfcn", -1);

         uarfcn.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("uarfcn", -1);
      }
      else throw new Asn1MissingRequiredException ("uarfcn");

      if (extbit) {

         // encode extension optional bits length

         int bitcnt = 0;
         if (extElem1 != null) bitcnt += extElem1.value.size();
         buffer.encodeSmallLength (bitcnt);

         // encode optional bits

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encodeExtBits (buffer);
         }

         // encode extension elements

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encode (buffer);
         }
      }
   }

}
