/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.lpp.LPP_PDU_Definitions;

import com.objsys.asn1j.runtime.*;

public class OTDOA_ReferenceCellInfoNB_r14_eutra_NumCRS_Ports_r14 extends Asn1Enumerated {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_LPP_PDU_DefinitionsRtkey._rtkey);
      Asn1Type._setLicLocation(_LPP_PDU_DefinitionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "ENUMERATED";
   }

   // Integer constants for switch-case
   public static final int _PORTS1_OR_2 = 0;
   public static final int _PORTS4 = 1;

   // Singleton instances of OTDOA_ReferenceCellInfoNB_r14_eutra_NumCRS_Ports_r14
   protected static final OTDOA_ReferenceCellInfoNB_r14_eutra_NumCRS_Ports_r14 _ports1_or_2 = new OTDOA_ReferenceCellInfoNB_r14_eutra_NumCRS_Ports_r14(0);
   protected static final OTDOA_ReferenceCellInfoNB_r14_eutra_NumCRS_Ports_r14 _ports4 = new OTDOA_ReferenceCellInfoNB_r14_eutra_NumCRS_Ports_r14(1);

   /**
    * Enumerated constructor: this object must be initialized with one 
    * of the following values:
    *   0
    *   1
    */
   protected OTDOA_ReferenceCellInfoNB_r14_eutra_NumCRS_Ports_r14 (int value_) {
      super (value_);
   }

   /**
    * Singleton accessor method for ports1_or_2.
    */
   public static OTDOA_ReferenceCellInfoNB_r14_eutra_NumCRS_Ports_r14 ports1_or_2() {
      return _ports1_or_2;
   }

   /**
    * Singleton accessor method for ports4.
    */
   public static OTDOA_ReferenceCellInfoNB_r14_eutra_NumCRS_Ports_r14 ports4() {
      return _ports4;
   }

   public static final Decoder DECODER = new Decoder();

   public static class Decoder implements Asn1PerDecoder{

      public Asn1Type decode(Asn1PerDecodeBuffer buffer) throws Asn1Exception, java.io.IOException
      {
         return OTDOA_ReferenceCellInfoNB_r14_eutra_NumCRS_Ports_r14.valueOf( OTDOA_ReferenceCellInfoNB_r14_eutra_NumCRS_Ports_r14.decodeEnumValue( buffer ) );
      }
   }

   /**
    * Returns the instance associated with the value passed.
    * If the value passed is invalid, an exception is thrown.
    */
   public static OTDOA_ReferenceCellInfoNB_r14_eutra_NumCRS_Ports_r14 valueOf (int _value)
      throws Asn1InvalidEnumException
   {
      switch ((int)_value) {
         case 0: return ports1_or_2();
         case 1: return ports4();
         default: throw new Asn1InvalidEnumException (_value);
      }
   }

   public static int decodeEnumValue (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      int ui;  // enum index
      int ret; // return value
      ui = (int) buffer.decodeConsWholeNumber (2);

      switch (ui) {
         case 0: ret =  0; break;
         case 1: ret =  1; break;
         default: throw new Asn1InvalidEnumException (ui);
      }

      buffer.setTypeCode (Asn1Type.ENUMERATED);
      return ret;
   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      int ui;  // enum index
      switch ((int)value) {
         case 0: ui = 0; /* ports1_or_2 */break;
         case 1: ui = 1; /* ports4 */break;
         default:
            throw new Asn1InvalidEnumException (value);
      }

      buffer.encodeConsWholeNumber (ui, 2);
   }

}
