/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.lpp.LPP_PDU_Definitions;

import com.objsys.asn1j.runtime.*;

public class PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16 extends Asn1Enumerated {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_LPP_PDU_DefinitionsRtkey._rtkey);
      Asn1Type._setLicLocation(_LPP_PDU_DefinitionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "ENUMERATED";
   }

   // Integer constants for switch-case
   public static final int _TYPE1 = 0;
   public static final int _TYPE2 = 1;

   // Singleton instances of PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16
   protected static final PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16 _type1 = new PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16(0);
   protected static final PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16 _type2 = new PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16(1);
   private static PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16 __undefined = new PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16(-999);

   /**
    * Enumerated constructor: this object must be initialized with one 
    * of the following values:
    *   0
    *   1
    */
   protected PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16 (int value_) {
      super (value_);
   }

   /**
    * Singleton accessor method for type1.
    */
   public static PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16 type1() {
      return _type1;
   }

   /**
    * Singleton accessor method for type2.
    */
   public static PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16 type2() {
      return _type2;
   }

   /** Undefined value. */
   protected static PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16 __undefined_() { return __undefined; }

   public static final Decoder DECODER = new Decoder();

   public static class Decoder implements Asn1PerDecoder{

      public Asn1Type decode(Asn1PerDecodeBuffer buffer) throws Asn1Exception, java.io.IOException
      {
         return PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16.valueOf( PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16.decodeEnumValue( buffer ) );
      }
   }

   /**
    * Returns the instance associated with the value passed.
    * If the value passed is invalid, an exception is thrown.
    */
   public static PRS_ProcessingCapabilityPerBand_r16_dl_PRS_BufferType_r16 valueOf (int _value)
   {
      switch ((int)_value) {
         case 0: return type1();
         case 1: return type2();
         default: return __undefined_();
      }
   }

   public static int decodeEnumValue (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      int ui;  // enum index
      int ret; // return value
      boolean extbit = buffer.decodeBit ("extbit");

      if (extbit) {
         ui = buffer.decodeSmallNonNegWholeNumber ();

         return 0x7fffffff;
      }
      else {
         ui = (int) buffer.decodeConsWholeNumber (2);

         switch (ui) {
            case 0: ret =  0; break;
            case 1: ret =  1; break;
            default: throw new Asn1InvalidEnumException (ui);
         }
      }

      buffer.setTypeCode (Asn1Type.ENUMERATED);
      return ret;
   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      int ui;  // enum index
      boolean extbit = false;

      switch ((int)value) {
         case 0: ui = 0; /* type1 */break;
         case 1: ui = 1; /* type2 */break;
         default:
            ui = (int) value;
            extbit = true;
      }

      buffer.encodeBit (extbit, "extbit");

      if (extbit) {
         buffer.encodeSmallNonNegWholeNumber (ui);
      }
      else {
         buffer.encodeConsWholeNumber (ui, 2);
      }
   }

}
