/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.lpp.LPP_PDU_Definitions;

import com.objsys.asn1j.runtime.*;

public class Sensor_MeasurementInformation_r13 extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_LPP_PDU_DefinitionsRtkey._rtkey);
      Asn1Type._setLicLocation(_LPP_PDU_DefinitionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "Sensor-MeasurementInformation-r13";
   }

   protected Asn1UTCTime measurementReferenceTime_r13;  // optional
   protected Asn1Integer uncompensatedBarometricPressure_r13;  // optional
   protected Sensor_MeasurementInformation_r13_uncertainty_r14 uncertainty_r14;  // optional
   protected Asn1Integer adjustment_r16;  // optional
   protected Asn1OpenExt extElem1;

   public Sensor_MeasurementInformation_r13 () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public Sensor_MeasurementInformation_r13 (
      Asn1UTCTime measurementReferenceTime_r13_,
      Asn1Integer uncompensatedBarometricPressure_r13_,
      Sensor_MeasurementInformation_r13_uncertainty_r14 uncertainty_r14_,
      Asn1Integer adjustment_r16_
   ) throws Asn1Exception {
      super();
      setMeasurementReferenceTime_r13 (measurementReferenceTime_r13_);
      setUncompensatedBarometricPressure_r13 (uncompensatedBarometricPressure_r13_);
      setUncertainty_r14 (uncertainty_r14_);
      setAdjustment_r16 (adjustment_r16_);
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public Sensor_MeasurementInformation_r13 (String measurementReferenceTime_r13_,
      long uncompensatedBarometricPressure_r13_,
      Sensor_MeasurementInformation_r13_uncertainty_r14 uncertainty_r14_,
      long adjustment_r16_
   ) throws Asn1Exception {
      super();
      setMeasurementReferenceTime_r13 (measurementReferenceTime_r13_);
      setUncompensatedBarometricPressure_r13 (uncompensatedBarometricPressure_r13_);
      setUncertainty_r14 (uncertainty_r14_);
      setAdjustment_r16 (adjustment_r16_);
   }

   public void init () {
      measurementReferenceTime_r13 = null;
      uncompensatedBarometricPressure_r13 = null;
      uncertainty_r14 = null;
      adjustment_r16 = null;
      extElem1 = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof Sensor_MeasurementInformation_r13) ) return false;

      Sensor_MeasurementInformation_r13 rhs = (Sensor_MeasurementInformation_r13) obj;

      if (measurementReferenceTime_r13 == null) {
         if (rhs.measurementReferenceTime_r13 != null) return false;
      }
      else {
         if (!measurementReferenceTime_r13.equals(rhs.measurementReferenceTime_r13)) {
            return false;
         }
      }

      if (uncompensatedBarometricPressure_r13 == null) {
         if (rhs.uncompensatedBarometricPressure_r13 != null) return false;
      }
      else {
         if (!uncompensatedBarometricPressure_r13.equals(rhs.uncompensatedBarometricPressure_r13)) {
            return false;
         }
      }

      if (uncertainty_r14 == null) {
         if (rhs.uncertainty_r14 != null) return false;
      }
      else {
         if (!uncertainty_r14.equals(rhs.uncertainty_r14)) {
            return false;
         }
      }

      if (adjustment_r16 == null) {
         if (rhs.adjustment_r16 != null) return false;
      }
      else {
         if (!adjustment_r16.equals(rhs.adjustment_r16)) {
            return false;
         }
      }

      if (extElem1 == null) {
         if (rhs.extElem1 != null) return false;
      }
      else {
         if (!extElem1.equals(rhs.extElem1)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (measurementReferenceTime_r13 != null) __code = 31*__code + measurementReferenceTime_r13.hashCode();
      if (uncompensatedBarometricPressure_r13 != null) __code = 31*__code + uncompensatedBarometricPressure_r13.hashCode();
      if (uncertainty_r14 != null) __code = 31*__code + uncertainty_r14.hashCode();
      if (adjustment_r16 != null) __code = 31*__code + adjustment_r16.hashCode();
      if (extElem1 != null) __code = 31*__code + extElem1.hashCode();

      return __code;
   }

   /**
    * Accessor/mutator methods for MeasurementReferenceTime_r13
    */
   public Asn1UTCTime getMeasurementReferenceTime_r13 () {
      return measurementReferenceTime_r13;
   }

   public void setMeasurementReferenceTime_r13 (Asn1UTCTime value) {
      this.measurementReferenceTime_r13 = value;
   }

   public void setMeasurementReferenceTime_r13 (String value) {
      setMeasurementReferenceTime_r13 (new Asn1UTCTime(value));
   }
   public boolean hasMeasurementReferenceTime_r13 () {
      return (measurementReferenceTime_r13 != null);
   }

   /**
    * Accessor/mutator methods for UncompensatedBarometricPressure_r13
    */
   public Asn1Integer getUncompensatedBarometricPressure_r13 () {
      return uncompensatedBarometricPressure_r13;
   }

   public void setUncompensatedBarometricPressure_r13 (Asn1Integer value) 
      throws Asn1Exception
   {
      if (!((value.value >= 30000 && value.value <= 115000))) {
         throw new Asn1ConsVioException ("value.value", value.value);
      }

      this.uncompensatedBarometricPressure_r13 = value;
   }

   public void setUncompensatedBarometricPressure_r13 (long value) 
      throws Asn1Exception
   {
      setUncompensatedBarometricPressure_r13 (new Asn1Integer(value));
   }
   public boolean hasUncompensatedBarometricPressure_r13 () {
      return (uncompensatedBarometricPressure_r13 != null);
   }

   /**
    * Accessor/mutator methods for Uncertainty_r14
    */
   public Sensor_MeasurementInformation_r13_uncertainty_r14 getUncertainty_r14 () {
      return uncertainty_r14;
   }

   public void setUncertainty_r14 (Sensor_MeasurementInformation_r13_uncertainty_r14 value) {
      this.uncertainty_r14 = value;
   }

   public boolean hasUncertainty_r14 () {
      return (uncertainty_r14 != null);
   }

   /**
    * Accessor/mutator methods for Adjustment_r16
    */
   public Asn1Integer getAdjustment_r16 () {
      return adjustment_r16;
   }

   public void setAdjustment_r16 (Asn1Integer value) 
      throws Asn1Exception
   {
      if (!((value.value >= -5000 && value.value <= 5000))) {
         throw new Asn1ConsVioException ("value.value", value.value);
      }

      this.adjustment_r16 = value;
   }

   public void setAdjustment_r16 (long value) 
      throws Asn1Exception
   {
      setAdjustment_r16 (new Asn1Integer(value));
   }
   public boolean hasAdjustment_r16 () {
      return (adjustment_r16 != null);
   }

   /**
    * Accessor/mutator methods for ExtElem1
    */
   public Asn1OpenExt getExtElem1 () {
      return extElem1;
   }

   public void setExtElem1 (Asn1OpenExt value) {
      this.extElem1 = value;
   }

   public int getElementCount() { return 5; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return measurementReferenceTime_r13;
         case 1: return uncompensatedBarometricPressure_r13;
         case 2: return uncertainty_r14;
         case 3: return adjustment_r16;
         case 4: return extElem1;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "measurementReferenceTime-r13";
         case 1: return "uncompensatedBarometricPressure-r13";
         case 2: return "uncertainty-r14";
         case 3: return "adjustment-r16";
         case 4: return null;
         default: return null;
      }
   }


   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      init ();

      // extension bit

      boolean extbit = buffer.decodeBit ("extbit");

      // optional bits

      boolean measurementReferenceTime_r13Present = buffer.decodeBit ("measurementReferenceTime_r13Present");
      boolean uncompensatedBarometricPressure_r13Present = buffer.decodeBit ("uncompensatedBarometricPressure_r13Present");

      // decode measurementReferenceTime_r13

      if (measurementReferenceTime_r13Present) {
         buffer.getContext().eventDispatcher.startElement("measurementReferenceTime_r13", -1);

         measurementReferenceTime_r13 = new Asn1UTCTime (true);
         measurementReferenceTime_r13.decode (buffer, (Asn1CharSet)null);
         buffer.getContext().eventDispatcher.endElement("measurementReferenceTime_r13", -1);
      }
      else {
         measurementReferenceTime_r13 = null;
      }

      // decode uncompensatedBarometricPressure_r13

      if (uncompensatedBarometricPressure_r13Present) {
         buffer.getContext().eventDispatcher.startElement("uncompensatedBarometricPressure_r13", -1);

         uncompensatedBarometricPressure_r13 = new Asn1Integer();
         uncompensatedBarometricPressure_r13.decode (buffer, 30000, 115000);
         buffer.getContext().eventDispatcher.endElement("uncompensatedBarometricPressure_r13", -1);
      }
      else {
         uncompensatedBarometricPressure_r13 = null;
      }

      if (extbit) {

         int bitcnt = buffer.decodeSmallLength(), i = 0;
         long bitidx = buffer.getBitOffset() + bitcnt;
         boolean[] bitmap = new boolean [bitcnt];

         if (i < bitcnt) bitmap[i++] = buffer.decodeBit ("uncertainty_r14Present");
         if (i < bitcnt) bitmap[i++] = buffer.decodeBit ("adjustment_r16Present");

         while (i < bitcnt) {
            bitmap[i++] = buffer.decodeBit ("unknown");
         }

         i = 0;

         // decode uncertainty_r14

         if (i < bitcnt && bitmap[i++]) {
            buffer.getContext().eventDispatcher.startElement("uncertainty_r14", -1);

            long _curidx = buffer.getBitOffset();
            bitidx = buffer.decodeExtLength ();
            if (bitidx - _curidx >= 131088)  {
               throw new Asn1Exception ("PER fragmentation not enabled: add -perindef to decode");
            }

            uncertainty_r14 = new Sensor_MeasurementInformation_r13_uncertainty_r14();
            uncertainty_r14.decode (buffer);

            buffer.moveBitCursor (bitidx);
            buffer.getContext().eventDispatcher.endElement("uncertainty_r14", -1);

         }
         else {
            uncertainty_r14 = null;
         }

         // decode adjustment_r16

         if (i < bitcnt && bitmap[i++]) {
            buffer.getContext().eventDispatcher.startElement("adjustment_r16", -1);

            long _curidx = buffer.getBitOffset();
            bitidx = buffer.decodeExtLength ();
            if (bitidx - _curidx >= 131088)  {
               throw new Asn1Exception ("PER fragmentation not enabled: add -perindef to decode");
            }

            adjustment_r16 = new Asn1Integer();
            adjustment_r16.decode (buffer, -5000, 5000);

            buffer.moveBitCursor (bitidx);
            buffer.getContext().eventDispatcher.endElement("adjustment_r16", -1);

         }
         else {
            adjustment_r16 = null;
         }

         // decode unknown extension elements

         if (i < bitcnt) {
            Asn1OpenType openType = null;
            extElem1 = new Asn1OpenExt();
            int j = 0;
            while (i < bitcnt) {
               if (bitmap[i]) {
                  buffer.getContext().eventDispatcher.startElement("...", -1);

                  openType = extElem1.decodeOpenType (buffer, true, j++);
               }
               else {
                  extElem1.setOpenType (null, j++);
               }
               i++;
            }
         }
         buffer.byteAlign ();

      }

   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      // extension bit

      boolean extbit = ((uncertainty_r14 != null) ||
      (adjustment_r16 != null) ||
      ((extElem1 != null) && (!extElem1.value.isEmpty()))
      );

      buffer.encodeBit (extbit, "extbit");

      // encode optional elements bit mask

      buffer.encodeBit ((measurementReferenceTime_r13 != null), null);
      buffer.encodeBit ((uncompensatedBarometricPressure_r13 != null), null);

      // encode measurementReferenceTime_r13

      if (measurementReferenceTime_r13 != null) {
         buffer.getContext().eventDispatcher.startElement("measurementReferenceTime_r13", -1);

         measurementReferenceTime_r13.encode (buffer, (Asn1CharSet)null);

         buffer.getContext().eventDispatcher.endElement("measurementReferenceTime_r13", -1);
      }

      // encode uncompensatedBarometricPressure_r13

      if (uncompensatedBarometricPressure_r13 != null) {
         buffer.getContext().eventDispatcher.startElement("uncompensatedBarometricPressure_r13", -1);

         uncompensatedBarometricPressure_r13.encode (buffer, 30000, 115000);

         buffer.getContext().eventDispatcher.endElement("uncompensatedBarometricPressure_r13", -1);
      }

      if (extbit) {

         // encode extension optional bits length

         int bitcnt = 2;
         if (extElem1 != null) bitcnt += extElem1.value.size();
         buffer.encodeSmallLength (bitcnt);

         // encode optional bits

         buffer.encodeBit ((uncertainty_r14 != null), null);
         buffer.encodeBit ((adjustment_r16 != null), null);

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encodeExtBits (buffer);
         }

         // encode extension elements

         Asn1PerEncodeBuffer mainBuffer = buffer;
         buffer = new Asn1PerEncodeBuffer (buffer.isAligned());

         // uncertainty_r14

         if (uncertainty_r14 != null) {
            buffer.reset();
            uncertainty_r14.encode (buffer);
            buffer.getContext().eventDispatcher.startElement("uncertainty_r14", -1);

            mainBuffer.encodeOpenType (buffer, null);

            buffer.getContext().eventDispatcher.endElement("uncertainty_r14", -1);
         }

         // adjustment_r16

         if (adjustment_r16 != null) {
            buffer.reset();
            adjustment_r16.encode (buffer, -5000, 5000);
            buffer.getContext().eventDispatcher.startElement("adjustment_r16", -1);

            mainBuffer.encodeOpenType (buffer, null);

            buffer.getContext().eventDispatcher.endElement("adjustment_r16", -1);
         }

         buffer = mainBuffer;

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encode (buffer);
         }
      }
   }

}
