/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.lpp.LPP_PDU_Definitions;

import com.objsys.asn1j.runtime.*;

public class SRS_CapabilityPerBand_r16 extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_LPP_PDU_DefinitionsRtkey._rtkey);
      Asn1Type._setLicLocation(_LPP_PDU_DefinitionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "SRS-CapabilityPerBand-r16";
   }

   protected FreqBandIndicatorNR_r16 freqBandIndicatorNR_r16;
   protected OLPC_SRS_Pos_r16 olpc_SRS_Pos_r16;  // optional
   protected SpatialRelationsSRS_Pos_r16 spatialRelationsSRS_Pos_r16;  // optional
   protected Asn1OpenExt extElem1;

   public SRS_CapabilityPerBand_r16 () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public SRS_CapabilityPerBand_r16 (
      FreqBandIndicatorNR_r16 freqBandIndicatorNR_r16_,
      OLPC_SRS_Pos_r16 olpc_SRS_Pos_r16_,
      SpatialRelationsSRS_Pos_r16 spatialRelationsSRS_Pos_r16_
   ) throws Asn1Exception {
      super();
      setFreqBandIndicatorNR_r16 (freqBandIndicatorNR_r16_);
      setOlpc_SRS_Pos_r16 (olpc_SRS_Pos_r16_);
      setSpatialRelationsSRS_Pos_r16 (spatialRelationsSRS_Pos_r16_);
   }

   /**
    * This constructor is for required elements only.  It sets 
    * all elements to references to the given objects
    */
   public SRS_CapabilityPerBand_r16 (
      FreqBandIndicatorNR_r16 freqBandIndicatorNR_r16_
   ) throws Asn1Exception {
      super();
      setFreqBandIndicatorNR_r16 (freqBandIndicatorNR_r16_);
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public SRS_CapabilityPerBand_r16 (long freqBandIndicatorNR_r16_,
      OLPC_SRS_Pos_r16 olpc_SRS_Pos_r16_,
      SpatialRelationsSRS_Pos_r16 spatialRelationsSRS_Pos_r16_
   ) throws Asn1Exception {
      super();
      setFreqBandIndicatorNR_r16 (freqBandIndicatorNR_r16_);
      setOlpc_SRS_Pos_r16 (olpc_SRS_Pos_r16_);
      setSpatialRelationsSRS_Pos_r16 (spatialRelationsSRS_Pos_r16_);
   }

   /**
    * This constructor is for required elements only.  It allows 
    * primitive data to be passed for all primitive elements.  
    * It will create new object wrappers for the primitive data 
    * and set other elements to references to the given objects. 
    */
   public SRS_CapabilityPerBand_r16 (
      long freqBandIndicatorNR_r16_
   ) throws Asn1Exception {
      super();
      setFreqBandIndicatorNR_r16 (freqBandIndicatorNR_r16_);
   }

   public void init () {
      freqBandIndicatorNR_r16 = null;
      olpc_SRS_Pos_r16 = null;
      spatialRelationsSRS_Pos_r16 = null;
      extElem1 = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof SRS_CapabilityPerBand_r16) ) return false;

      SRS_CapabilityPerBand_r16 rhs = (SRS_CapabilityPerBand_r16) obj;

      if (freqBandIndicatorNR_r16 == null) {
         if (rhs.freqBandIndicatorNR_r16 != null) return false;
      }
      else {
         if (!freqBandIndicatorNR_r16.equals(rhs.freqBandIndicatorNR_r16)) {
            return false;
         }
      }

      if (olpc_SRS_Pos_r16 == null) {
         if (rhs.olpc_SRS_Pos_r16 != null) return false;
      }
      else {
         if (!olpc_SRS_Pos_r16.equals(rhs.olpc_SRS_Pos_r16)) {
            return false;
         }
      }

      if (spatialRelationsSRS_Pos_r16 == null) {
         if (rhs.spatialRelationsSRS_Pos_r16 != null) return false;
      }
      else {
         if (!spatialRelationsSRS_Pos_r16.equals(rhs.spatialRelationsSRS_Pos_r16)) {
            return false;
         }
      }

      if (extElem1 == null) {
         if (rhs.extElem1 != null) return false;
      }
      else {
         if (!extElem1.equals(rhs.extElem1)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (freqBandIndicatorNR_r16 != null) __code = 31*__code + freqBandIndicatorNR_r16.hashCode();
      if (olpc_SRS_Pos_r16 != null) __code = 31*__code + olpc_SRS_Pos_r16.hashCode();
      if (spatialRelationsSRS_Pos_r16 != null) __code = 31*__code + spatialRelationsSRS_Pos_r16.hashCode();
      if (extElem1 != null) __code = 31*__code + extElem1.hashCode();

      return __code;
   }

   /**
    * Accessor/mutator methods for FreqBandIndicatorNR_r16
    */
   public FreqBandIndicatorNR_r16 getFreqBandIndicatorNR_r16 () {
      return freqBandIndicatorNR_r16;
   }

   public void setFreqBandIndicatorNR_r16 (FreqBandIndicatorNR_r16 value) 
      throws Asn1Exception
   {
      if (!((value.value >= 1 && value.value <= 1024))) {
         throw new Asn1ConsVioException ("value.value", value.value);
      }

      this.freqBandIndicatorNR_r16 = value;
   }

   public void setFreqBandIndicatorNR_r16 (long value) 
      throws Asn1Exception
   {
      setFreqBandIndicatorNR_r16 (new FreqBandIndicatorNR_r16(value));
   }

   /**
    * Accessor/mutator methods for Olpc_SRS_Pos_r16
    */
   public OLPC_SRS_Pos_r16 getOlpc_SRS_Pos_r16 () {
      return olpc_SRS_Pos_r16;
   }

   public void setOlpc_SRS_Pos_r16 (OLPC_SRS_Pos_r16 value) {
      this.olpc_SRS_Pos_r16 = value;
   }

   public boolean hasOlpc_SRS_Pos_r16 () {
      return (olpc_SRS_Pos_r16 != null);
   }

   /**
    * Accessor/mutator methods for SpatialRelationsSRS_Pos_r16
    */
   public SpatialRelationsSRS_Pos_r16 getSpatialRelationsSRS_Pos_r16 () {
      return spatialRelationsSRS_Pos_r16;
   }

   public void setSpatialRelationsSRS_Pos_r16 (SpatialRelationsSRS_Pos_r16 value) {
      this.spatialRelationsSRS_Pos_r16 = value;
   }

   public boolean hasSpatialRelationsSRS_Pos_r16 () {
      return (spatialRelationsSRS_Pos_r16 != null);
   }

   /**
    * Accessor/mutator methods for ExtElem1
    */
   public Asn1OpenExt getExtElem1 () {
      return extElem1;
   }

   public void setExtElem1 (Asn1OpenExt value) {
      this.extElem1 = value;
   }

   public int getElementCount() { return 4; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return freqBandIndicatorNR_r16;
         case 1: return olpc_SRS_Pos_r16;
         case 2: return spatialRelationsSRS_Pos_r16;
         case 3: return extElem1;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "freqBandIndicatorNR-r16";
         case 1: return "olpc-SRS-Pos-r16";
         case 2: return "spatialRelationsSRS-Pos-r16";
         case 3: return null;
         default: return null;
      }
   }


   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      init ();

      // extension bit

      boolean extbit = buffer.decodeBit ("extbit");

      // optional bits

      boolean olpc_SRS_Pos_r16Present = buffer.decodeBit ("olpc_SRS_Pos_r16Present");
      boolean spatialRelationsSRS_Pos_r16Present = buffer.decodeBit ("spatialRelationsSRS_Pos_r16Present");

      // decode freqBandIndicatorNR_r16

      buffer.getContext().eventDispatcher.startElement("freqBandIndicatorNR_r16", -1);

      freqBandIndicatorNR_r16 = new FreqBandIndicatorNR_r16();
      freqBandIndicatorNR_r16.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("freqBandIndicatorNR_r16", -1);

      // decode olpc_SRS_Pos_r16

      if (olpc_SRS_Pos_r16Present) {
         buffer.getContext().eventDispatcher.startElement("olpc_SRS_Pos_r16", -1);

         olpc_SRS_Pos_r16 = new OLPC_SRS_Pos_r16();
         olpc_SRS_Pos_r16.decode (buffer);
         buffer.getContext().eventDispatcher.endElement("olpc_SRS_Pos_r16", -1);
      }
      else {
         olpc_SRS_Pos_r16 = null;
      }

      // decode spatialRelationsSRS_Pos_r16

      if (spatialRelationsSRS_Pos_r16Present) {
         buffer.getContext().eventDispatcher.startElement("spatialRelationsSRS_Pos_r16", -1);

         spatialRelationsSRS_Pos_r16 = new SpatialRelationsSRS_Pos_r16();
         spatialRelationsSRS_Pos_r16.decode (buffer);
         buffer.getContext().eventDispatcher.endElement("spatialRelationsSRS_Pos_r16", -1);
      }
      else {
         spatialRelationsSRS_Pos_r16 = null;
      }

      if (extbit) {

         int bitcnt = buffer.decodeSmallLength(), i = 0;
         long bitidx = buffer.getBitOffset() + bitcnt;
         boolean[] bitmap = new boolean [bitcnt];

         while (i < bitcnt) {
            bitmap[i++] = buffer.decodeBit ("unknown");
         }

         i = 0;

         // decode unknown extension elements

         if (i < bitcnt) {
            Asn1OpenType openType = null;
            extElem1 = new Asn1OpenExt();
            int j = 0;
            while (i < bitcnt) {
               if (bitmap[i]) {
                  buffer.getContext().eventDispatcher.startElement("...", -1);

                  openType = extElem1.decodeOpenType (buffer, true, j++);
               }
               else {
                  extElem1.setOpenType (null, j++);
               }
               i++;
            }
         }
         buffer.byteAlign ();

      }

   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      // extension bit

      boolean extbit = (((extElem1 != null) && (!extElem1.value.isEmpty()))
      );

      buffer.encodeBit (extbit, "extbit");

      // encode optional elements bit mask

      buffer.encodeBit ((olpc_SRS_Pos_r16 != null), null);
      buffer.encodeBit ((spatialRelationsSRS_Pos_r16 != null), null);

      // encode freqBandIndicatorNR_r16

      if (freqBandIndicatorNR_r16 != null) {
         buffer.getContext().eventDispatcher.startElement("freqBandIndicatorNR_r16", -1);

         freqBandIndicatorNR_r16.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("freqBandIndicatorNR_r16", -1);
      }
      else throw new Asn1MissingRequiredException ("freqBandIndicatorNR_r16");

      // encode olpc_SRS_Pos_r16

      if (olpc_SRS_Pos_r16 != null) {
         buffer.getContext().eventDispatcher.startElement("olpc_SRS_Pos_r16", -1);

         olpc_SRS_Pos_r16.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("olpc_SRS_Pos_r16", -1);
      }

      // encode spatialRelationsSRS_Pos_r16

      if (spatialRelationsSRS_Pos_r16 != null) {
         buffer.getContext().eventDispatcher.startElement("spatialRelationsSRS_Pos_r16", -1);

         spatialRelationsSRS_Pos_r16.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("spatialRelationsSRS_Pos_r16", -1);
      }

      if (extbit) {

         // encode extension optional bits length

         int bitcnt = 0;
         if (extElem1 != null) bitcnt += extElem1.value.size();
         buffer.encodeSmallLength (bitcnt);

         // encode optional bits

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encodeExtBits (buffer);
         }

         // encode extension elements

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encode (buffer);
         }
      }
   }

}
