/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.lpp.LPP_PDU_Definitions;

import com.objsys.asn1j.runtime.*;

public class SupportedChannels_11a_r14 extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_LPP_PDU_DefinitionsRtkey._rtkey);
      Asn1Type._setLicLocation(_LPP_PDU_DefinitionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "SupportedChannels-11a-r14";
   }

   protected Asn1Boolean ch34_r14;
   protected Asn1Boolean ch36_r14;
   protected Asn1Boolean ch38_r14;
   protected Asn1Boolean ch40_r14;
   protected Asn1Boolean ch42_r14;
   protected Asn1Boolean ch44_r14;
   protected Asn1Boolean ch46_r14;
   protected Asn1Boolean ch48_r14;
   protected Asn1Boolean ch52_r14;
   protected Asn1Boolean ch56_r14;
   protected Asn1Boolean ch60_r14;
   protected Asn1Boolean ch64_r14;
   protected Asn1Boolean ch149_r14;
   protected Asn1Boolean ch153_r14;
   protected Asn1Boolean ch157_r14;
   protected Asn1Boolean ch161_r14;

   public SupportedChannels_11a_r14 () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public SupportedChannels_11a_r14 (
      Asn1Boolean ch34_r14_,
      Asn1Boolean ch36_r14_,
      Asn1Boolean ch38_r14_,
      Asn1Boolean ch40_r14_,
      Asn1Boolean ch42_r14_,
      Asn1Boolean ch44_r14_,
      Asn1Boolean ch46_r14_,
      Asn1Boolean ch48_r14_,
      Asn1Boolean ch52_r14_,
      Asn1Boolean ch56_r14_,
      Asn1Boolean ch60_r14_,
      Asn1Boolean ch64_r14_,
      Asn1Boolean ch149_r14_,
      Asn1Boolean ch153_r14_,
      Asn1Boolean ch157_r14_,
      Asn1Boolean ch161_r14_
   ) {
      super();
      setCh34_r14 (ch34_r14_);
      setCh36_r14 (ch36_r14_);
      setCh38_r14 (ch38_r14_);
      setCh40_r14 (ch40_r14_);
      setCh42_r14 (ch42_r14_);
      setCh44_r14 (ch44_r14_);
      setCh46_r14 (ch46_r14_);
      setCh48_r14 (ch48_r14_);
      setCh52_r14 (ch52_r14_);
      setCh56_r14 (ch56_r14_);
      setCh60_r14 (ch60_r14_);
      setCh64_r14 (ch64_r14_);
      setCh149_r14 (ch149_r14_);
      setCh153_r14 (ch153_r14_);
      setCh157_r14 (ch157_r14_);
      setCh161_r14 (ch161_r14_);
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public SupportedChannels_11a_r14 (boolean ch34_r14_,
      boolean ch36_r14_,
      boolean ch38_r14_,
      boolean ch40_r14_,
      boolean ch42_r14_,
      boolean ch44_r14_,
      boolean ch46_r14_,
      boolean ch48_r14_,
      boolean ch52_r14_,
      boolean ch56_r14_,
      boolean ch60_r14_,
      boolean ch64_r14_,
      boolean ch149_r14_,
      boolean ch153_r14_,
      boolean ch157_r14_,
      boolean ch161_r14_
   ) {
      super();
      setCh34_r14 (ch34_r14_);
      setCh36_r14 (ch36_r14_);
      setCh38_r14 (ch38_r14_);
      setCh40_r14 (ch40_r14_);
      setCh42_r14 (ch42_r14_);
      setCh44_r14 (ch44_r14_);
      setCh46_r14 (ch46_r14_);
      setCh48_r14 (ch48_r14_);
      setCh52_r14 (ch52_r14_);
      setCh56_r14 (ch56_r14_);
      setCh60_r14 (ch60_r14_);
      setCh64_r14 (ch64_r14_);
      setCh149_r14 (ch149_r14_);
      setCh153_r14 (ch153_r14_);
      setCh157_r14 (ch157_r14_);
      setCh161_r14 (ch161_r14_);
   }

   public void init () {
      ch34_r14 = null;
      ch36_r14 = null;
      ch38_r14 = null;
      ch40_r14 = null;
      ch42_r14 = null;
      ch44_r14 = null;
      ch46_r14 = null;
      ch48_r14 = null;
      ch52_r14 = null;
      ch56_r14 = null;
      ch60_r14 = null;
      ch64_r14 = null;
      ch149_r14 = null;
      ch153_r14 = null;
      ch157_r14 = null;
      ch161_r14 = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof SupportedChannels_11a_r14) ) return false;

      SupportedChannels_11a_r14 rhs = (SupportedChannels_11a_r14) obj;

      if (ch34_r14 == null) {
         if (rhs.ch34_r14 != null) return false;
      }
      else {
         if (!ch34_r14.equals(rhs.ch34_r14)) {
            return false;
         }
      }

      if (ch36_r14 == null) {
         if (rhs.ch36_r14 != null) return false;
      }
      else {
         if (!ch36_r14.equals(rhs.ch36_r14)) {
            return false;
         }
      }

      if (ch38_r14 == null) {
         if (rhs.ch38_r14 != null) return false;
      }
      else {
         if (!ch38_r14.equals(rhs.ch38_r14)) {
            return false;
         }
      }

      if (ch40_r14 == null) {
         if (rhs.ch40_r14 != null) return false;
      }
      else {
         if (!ch40_r14.equals(rhs.ch40_r14)) {
            return false;
         }
      }

      if (ch42_r14 == null) {
         if (rhs.ch42_r14 != null) return false;
      }
      else {
         if (!ch42_r14.equals(rhs.ch42_r14)) {
            return false;
         }
      }

      if (ch44_r14 == null) {
         if (rhs.ch44_r14 != null) return false;
      }
      else {
         if (!ch44_r14.equals(rhs.ch44_r14)) {
            return false;
         }
      }

      if (ch46_r14 == null) {
         if (rhs.ch46_r14 != null) return false;
      }
      else {
         if (!ch46_r14.equals(rhs.ch46_r14)) {
            return false;
         }
      }

      if (ch48_r14 == null) {
         if (rhs.ch48_r14 != null) return false;
      }
      else {
         if (!ch48_r14.equals(rhs.ch48_r14)) {
            return false;
         }
      }

      if (ch52_r14 == null) {
         if (rhs.ch52_r14 != null) return false;
      }
      else {
         if (!ch52_r14.equals(rhs.ch52_r14)) {
            return false;
         }
      }

      if (ch56_r14 == null) {
         if (rhs.ch56_r14 != null) return false;
      }
      else {
         if (!ch56_r14.equals(rhs.ch56_r14)) {
            return false;
         }
      }

      if (ch60_r14 == null) {
         if (rhs.ch60_r14 != null) return false;
      }
      else {
         if (!ch60_r14.equals(rhs.ch60_r14)) {
            return false;
         }
      }

      if (ch64_r14 == null) {
         if (rhs.ch64_r14 != null) return false;
      }
      else {
         if (!ch64_r14.equals(rhs.ch64_r14)) {
            return false;
         }
      }

      if (ch149_r14 == null) {
         if (rhs.ch149_r14 != null) return false;
      }
      else {
         if (!ch149_r14.equals(rhs.ch149_r14)) {
            return false;
         }
      }

      if (ch153_r14 == null) {
         if (rhs.ch153_r14 != null) return false;
      }
      else {
         if (!ch153_r14.equals(rhs.ch153_r14)) {
            return false;
         }
      }

      if (ch157_r14 == null) {
         if (rhs.ch157_r14 != null) return false;
      }
      else {
         if (!ch157_r14.equals(rhs.ch157_r14)) {
            return false;
         }
      }

      if (ch161_r14 == null) {
         if (rhs.ch161_r14 != null) return false;
      }
      else {
         if (!ch161_r14.equals(rhs.ch161_r14)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (ch34_r14 != null) __code = 31*__code + ch34_r14.hashCode();
      if (ch36_r14 != null) __code = 31*__code + ch36_r14.hashCode();
      if (ch38_r14 != null) __code = 31*__code + ch38_r14.hashCode();
      if (ch40_r14 != null) __code = 31*__code + ch40_r14.hashCode();
      if (ch42_r14 != null) __code = 31*__code + ch42_r14.hashCode();
      if (ch44_r14 != null) __code = 31*__code + ch44_r14.hashCode();
      if (ch46_r14 != null) __code = 31*__code + ch46_r14.hashCode();
      if (ch48_r14 != null) __code = 31*__code + ch48_r14.hashCode();
      if (ch52_r14 != null) __code = 31*__code + ch52_r14.hashCode();
      if (ch56_r14 != null) __code = 31*__code + ch56_r14.hashCode();
      if (ch60_r14 != null) __code = 31*__code + ch60_r14.hashCode();
      if (ch64_r14 != null) __code = 31*__code + ch64_r14.hashCode();
      if (ch149_r14 != null) __code = 31*__code + ch149_r14.hashCode();
      if (ch153_r14 != null) __code = 31*__code + ch153_r14.hashCode();
      if (ch157_r14 != null) __code = 31*__code + ch157_r14.hashCode();
      if (ch161_r14 != null) __code = 31*__code + ch161_r14.hashCode();

      return __code;
   }

   /**
    * Accessor/mutator methods for Ch34_r14
    */
   public Asn1Boolean getCh34_r14 () {
      return ch34_r14;
   }

   public void setCh34_r14 (Asn1Boolean value) {
      this.ch34_r14 = value;
   }

   public void setCh34_r14 (boolean value) {
      setCh34_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch36_r14
    */
   public Asn1Boolean getCh36_r14 () {
      return ch36_r14;
   }

   public void setCh36_r14 (Asn1Boolean value) {
      this.ch36_r14 = value;
   }

   public void setCh36_r14 (boolean value) {
      setCh36_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch38_r14
    */
   public Asn1Boolean getCh38_r14 () {
      return ch38_r14;
   }

   public void setCh38_r14 (Asn1Boolean value) {
      this.ch38_r14 = value;
   }

   public void setCh38_r14 (boolean value) {
      setCh38_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch40_r14
    */
   public Asn1Boolean getCh40_r14 () {
      return ch40_r14;
   }

   public void setCh40_r14 (Asn1Boolean value) {
      this.ch40_r14 = value;
   }

   public void setCh40_r14 (boolean value) {
      setCh40_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch42_r14
    */
   public Asn1Boolean getCh42_r14 () {
      return ch42_r14;
   }

   public void setCh42_r14 (Asn1Boolean value) {
      this.ch42_r14 = value;
   }

   public void setCh42_r14 (boolean value) {
      setCh42_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch44_r14
    */
   public Asn1Boolean getCh44_r14 () {
      return ch44_r14;
   }

   public void setCh44_r14 (Asn1Boolean value) {
      this.ch44_r14 = value;
   }

   public void setCh44_r14 (boolean value) {
      setCh44_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch46_r14
    */
   public Asn1Boolean getCh46_r14 () {
      return ch46_r14;
   }

   public void setCh46_r14 (Asn1Boolean value) {
      this.ch46_r14 = value;
   }

   public void setCh46_r14 (boolean value) {
      setCh46_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch48_r14
    */
   public Asn1Boolean getCh48_r14 () {
      return ch48_r14;
   }

   public void setCh48_r14 (Asn1Boolean value) {
      this.ch48_r14 = value;
   }

   public void setCh48_r14 (boolean value) {
      setCh48_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch52_r14
    */
   public Asn1Boolean getCh52_r14 () {
      return ch52_r14;
   }

   public void setCh52_r14 (Asn1Boolean value) {
      this.ch52_r14 = value;
   }

   public void setCh52_r14 (boolean value) {
      setCh52_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch56_r14
    */
   public Asn1Boolean getCh56_r14 () {
      return ch56_r14;
   }

   public void setCh56_r14 (Asn1Boolean value) {
      this.ch56_r14 = value;
   }

   public void setCh56_r14 (boolean value) {
      setCh56_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch60_r14
    */
   public Asn1Boolean getCh60_r14 () {
      return ch60_r14;
   }

   public void setCh60_r14 (Asn1Boolean value) {
      this.ch60_r14 = value;
   }

   public void setCh60_r14 (boolean value) {
      setCh60_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch64_r14
    */
   public Asn1Boolean getCh64_r14 () {
      return ch64_r14;
   }

   public void setCh64_r14 (Asn1Boolean value) {
      this.ch64_r14 = value;
   }

   public void setCh64_r14 (boolean value) {
      setCh64_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch149_r14
    */
   public Asn1Boolean getCh149_r14 () {
      return ch149_r14;
   }

   public void setCh149_r14 (Asn1Boolean value) {
      this.ch149_r14 = value;
   }

   public void setCh149_r14 (boolean value) {
      setCh149_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch153_r14
    */
   public Asn1Boolean getCh153_r14 () {
      return ch153_r14;
   }

   public void setCh153_r14 (Asn1Boolean value) {
      this.ch153_r14 = value;
   }

   public void setCh153_r14 (boolean value) {
      setCh153_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch157_r14
    */
   public Asn1Boolean getCh157_r14 () {
      return ch157_r14;
   }

   public void setCh157_r14 (Asn1Boolean value) {
      this.ch157_r14 = value;
   }

   public void setCh157_r14 (boolean value) {
      setCh157_r14 (new Asn1Boolean(value));
   }

   /**
    * Accessor/mutator methods for Ch161_r14
    */
   public Asn1Boolean getCh161_r14 () {
      return ch161_r14;
   }

   public void setCh161_r14 (Asn1Boolean value) {
      this.ch161_r14 = value;
   }

   public void setCh161_r14 (boolean value) {
      setCh161_r14 (new Asn1Boolean(value));
   }

   public int getElementCount() { return 16; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return ch34_r14;
         case 1: return ch36_r14;
         case 2: return ch38_r14;
         case 3: return ch40_r14;
         case 4: return ch42_r14;
         case 5: return ch44_r14;
         case 6: return ch46_r14;
         case 7: return ch48_r14;
         case 8: return ch52_r14;
         case 9: return ch56_r14;
         case 10: return ch60_r14;
         case 11: return ch64_r14;
         case 12: return ch149_r14;
         case 13: return ch153_r14;
         case 14: return ch157_r14;
         case 15: return ch161_r14;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "ch34-r14";
         case 1: return "ch36-r14";
         case 2: return "ch38-r14";
         case 3: return "ch40-r14";
         case 4: return "ch42-r14";
         case 5: return "ch44-r14";
         case 6: return "ch46-r14";
         case 7: return "ch48-r14";
         case 8: return "ch52-r14";
         case 9: return "ch56-r14";
         case 10: return "ch60-r14";
         case 11: return "ch64-r14";
         case 12: return "ch149-r14";
         case 13: return "ch153-r14";
         case 14: return "ch157-r14";
         case 15: return "ch161-r14";
         default: return null;
      }
   }


   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      init ();

      // decode ch34_r14

      buffer.getContext().eventDispatcher.startElement("ch34_r14", -1);

      ch34_r14 = new Asn1Boolean();
      ch34_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch34_r14", -1);

      // decode ch36_r14

      buffer.getContext().eventDispatcher.startElement("ch36_r14", -1);

      ch36_r14 = new Asn1Boolean();
      ch36_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch36_r14", -1);

      // decode ch38_r14

      buffer.getContext().eventDispatcher.startElement("ch38_r14", -1);

      ch38_r14 = new Asn1Boolean();
      ch38_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch38_r14", -1);

      // decode ch40_r14

      buffer.getContext().eventDispatcher.startElement("ch40_r14", -1);

      ch40_r14 = new Asn1Boolean();
      ch40_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch40_r14", -1);

      // decode ch42_r14

      buffer.getContext().eventDispatcher.startElement("ch42_r14", -1);

      ch42_r14 = new Asn1Boolean();
      ch42_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch42_r14", -1);

      // decode ch44_r14

      buffer.getContext().eventDispatcher.startElement("ch44_r14", -1);

      ch44_r14 = new Asn1Boolean();
      ch44_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch44_r14", -1);

      // decode ch46_r14

      buffer.getContext().eventDispatcher.startElement("ch46_r14", -1);

      ch46_r14 = new Asn1Boolean();
      ch46_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch46_r14", -1);

      // decode ch48_r14

      buffer.getContext().eventDispatcher.startElement("ch48_r14", -1);

      ch48_r14 = new Asn1Boolean();
      ch48_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch48_r14", -1);

      // decode ch52_r14

      buffer.getContext().eventDispatcher.startElement("ch52_r14", -1);

      ch52_r14 = new Asn1Boolean();
      ch52_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch52_r14", -1);

      // decode ch56_r14

      buffer.getContext().eventDispatcher.startElement("ch56_r14", -1);

      ch56_r14 = new Asn1Boolean();
      ch56_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch56_r14", -1);

      // decode ch60_r14

      buffer.getContext().eventDispatcher.startElement("ch60_r14", -1);

      ch60_r14 = new Asn1Boolean();
      ch60_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch60_r14", -1);

      // decode ch64_r14

      buffer.getContext().eventDispatcher.startElement("ch64_r14", -1);

      ch64_r14 = new Asn1Boolean();
      ch64_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch64_r14", -1);

      // decode ch149_r14

      buffer.getContext().eventDispatcher.startElement("ch149_r14", -1);

      ch149_r14 = new Asn1Boolean();
      ch149_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch149_r14", -1);

      // decode ch153_r14

      buffer.getContext().eventDispatcher.startElement("ch153_r14", -1);

      ch153_r14 = new Asn1Boolean();
      ch153_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch153_r14", -1);

      // decode ch157_r14

      buffer.getContext().eventDispatcher.startElement("ch157_r14", -1);

      ch157_r14 = new Asn1Boolean();
      ch157_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch157_r14", -1);

      // decode ch161_r14

      buffer.getContext().eventDispatcher.startElement("ch161_r14", -1);

      ch161_r14 = new Asn1Boolean();
      ch161_r14.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("ch161_r14", -1);

   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      // encode ch34_r14

      if (ch34_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch34_r14", -1);

         ch34_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch34_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch34_r14");

      // encode ch36_r14

      if (ch36_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch36_r14", -1);

         ch36_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch36_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch36_r14");

      // encode ch38_r14

      if (ch38_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch38_r14", -1);

         ch38_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch38_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch38_r14");

      // encode ch40_r14

      if (ch40_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch40_r14", -1);

         ch40_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch40_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch40_r14");

      // encode ch42_r14

      if (ch42_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch42_r14", -1);

         ch42_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch42_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch42_r14");

      // encode ch44_r14

      if (ch44_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch44_r14", -1);

         ch44_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch44_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch44_r14");

      // encode ch46_r14

      if (ch46_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch46_r14", -1);

         ch46_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch46_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch46_r14");

      // encode ch48_r14

      if (ch48_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch48_r14", -1);

         ch48_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch48_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch48_r14");

      // encode ch52_r14

      if (ch52_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch52_r14", -1);

         ch52_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch52_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch52_r14");

      // encode ch56_r14

      if (ch56_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch56_r14", -1);

         ch56_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch56_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch56_r14");

      // encode ch60_r14

      if (ch60_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch60_r14", -1);

         ch60_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch60_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch60_r14");

      // encode ch64_r14

      if (ch64_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch64_r14", -1);

         ch64_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch64_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch64_r14");

      // encode ch149_r14

      if (ch149_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch149_r14", -1);

         ch149_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch149_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch149_r14");

      // encode ch153_r14

      if (ch153_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch153_r14", -1);

         ch153_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch153_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch153_r14");

      // encode ch157_r14

      if (ch157_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch157_r14", -1);

         ch157_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch157_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch157_r14");

      // encode ch161_r14

      if (ch161_r14 != null) {
         buffer.getContext().eventDispatcher.startElement("ch161_r14", -1);

         ch161_r14.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("ch161_r14", -1);
      }
      else throw new Asn1MissingRequiredException ("ch161_r14");

   }

}
