/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.lpp.LPP_PDU_Definitions;

import com.objsys.asn1j.runtime.*;

public class TBS_TargetDeviceErrorCauses_r13_cause_r13 extends Asn1Enumerated {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_LPP_PDU_DefinitionsRtkey._rtkey);
      Asn1Type._setLicLocation(_LPP_PDU_DefinitionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "ENUMERATED";
   }

   // Integer constants for switch-case
   public static final int _UNDEFINED_ = 0;
   public static final int _THEREWERENOTENOUGHMBSBEACONSRECEIVED = 1;
   public static final int _ASSISTANCEDATAMISSING_V1420 = 2;

   // Singleton instances of TBS_TargetDeviceErrorCauses_r13_cause_r13
   protected static final TBS_TargetDeviceErrorCauses_r13_cause_r13 _undefined_ = new TBS_TargetDeviceErrorCauses_r13_cause_r13(0);
   protected static final TBS_TargetDeviceErrorCauses_r13_cause_r13 _thereWereNotEnoughMBSBeaconsReceived = new TBS_TargetDeviceErrorCauses_r13_cause_r13(1);
   protected static final TBS_TargetDeviceErrorCauses_r13_cause_r13 _assistanceDataMissing_v1420 = new TBS_TargetDeviceErrorCauses_r13_cause_r13(2);
   private static TBS_TargetDeviceErrorCauses_r13_cause_r13 __undefined = new TBS_TargetDeviceErrorCauses_r13_cause_r13(-999);

   /**
    * Enumerated constructor: this object must be initialized with one 
    * of the following values:
    *   0
    *   1
    *   2
    */
   protected TBS_TargetDeviceErrorCauses_r13_cause_r13 (int value_) {
      super (value_);
   }

   /**
    * Singleton accessor method for undefined_.
    */
   public static TBS_TargetDeviceErrorCauses_r13_cause_r13 undefined_() {
      return _undefined_;
   }

   /**
    * Singleton accessor method for thereWereNotEnoughMBSBeaconsReceived.
    */
   public static TBS_TargetDeviceErrorCauses_r13_cause_r13 thereWereNotEnoughMBSBeaconsReceived() {
      return _thereWereNotEnoughMBSBeaconsReceived;
   }

   /**
    * Singleton accessor method for assistanceDataMissing_v1420.
    */
   public static TBS_TargetDeviceErrorCauses_r13_cause_r13 assistanceDataMissing_v1420() {
      return _assistanceDataMissing_v1420;
   }

   /** Undefined value. */
   protected static TBS_TargetDeviceErrorCauses_r13_cause_r13 __undefined_() { return __undefined; }

   public static final Decoder DECODER = new Decoder();

   public static class Decoder implements Asn1PerDecoder{

      public Asn1Type decode(Asn1PerDecodeBuffer buffer) throws Asn1Exception, java.io.IOException
      {
         return TBS_TargetDeviceErrorCauses_r13_cause_r13.valueOf( TBS_TargetDeviceErrorCauses_r13_cause_r13.decodeEnumValue( buffer ) );
      }
   }

   /**
    * Returns the instance associated with the value passed.
    * If the value passed is invalid, an exception is thrown.
    */
   public static TBS_TargetDeviceErrorCauses_r13_cause_r13 valueOf (int _value)
   {
      switch ((int)_value) {
         case 0: return undefined_();
         case 1: return thereWereNotEnoughMBSBeaconsReceived();
         case 2: return assistanceDataMissing_v1420();
         default: return __undefined_();
      }
   }

   public static int decodeEnumValue (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      int ui;  // enum index
      int ret; // return value
      boolean extbit = buffer.decodeBit ("extbit");

      if (extbit) {
         ui = buffer.decodeSmallNonNegWholeNumber ();

         switch (ui) {
            case 0: ret = 2; break;
            default: ret = 0x7fffffff; break;
         }
      }
      else {
         ui = (int) buffer.decodeConsWholeNumber (2);

         switch (ui) {
            case 0: ret =  0; break;
            case 1: ret =  1; break;
            default: throw new Asn1InvalidEnumException (ui);
         }
      }

      buffer.setTypeCode (Asn1Type.ENUMERATED);
      return ret;
   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      int ui;  // enum index
      boolean extbit = false;

      switch ((int)value) {
         case 0: ui = 0; /* undefined_ */break;
         case 1: ui = 1; /* thereWereNotEnoughMBSBeaconsReceived */break;
         case 2: ui = 0; /* assistanceDataMissing_v1420 */extbit = true; break;
         default:
            ui = (int) value;
            extbit = true;
      }

      buffer.encodeBit (extbit, "extbit");

      if (extbit) {
         buffer.encodeSmallNonNegWholeNumber (ui);
      }
      else {
         buffer.encodeConsWholeNumber (ui, 2);
      }
   }

}
