/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.supl.ULP_Version_2_message_extensions;

import com.objsys.asn1j.runtime.*;

public class AllowedReportingType extends Asn1Enumerated {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_ULP_Version_2_message_extensionsRtkey._rtkey);
      Asn1Type._setLicLocation(_ULP_Version_2_message_extensionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "AllowedReportingType";
   }

   // Integer constants for switch-case
   public static final int _POSITIONSONLY = 0;
   public static final int _MEASUREMENTSONLY = 1;
   public static final int _POSITIONSANDMEASUREMENTS = 2;

   // Singleton instances of AllowedReportingType
   protected static final AllowedReportingType _positionsOnly = new AllowedReportingType(0);
   protected static final AllowedReportingType _measurementsOnly = new AllowedReportingType(1);
   protected static final AllowedReportingType _positionsAndMeasurements = new AllowedReportingType(2);
   private static AllowedReportingType __undefined = new AllowedReportingType(-999);

   /**
    * Enumerated constructor: this object must be initialized with one 
    * of the following values:
    *   0
    *   1
    *   2
    */
   protected AllowedReportingType (int value_) {
      super (value_);
   }

   /**
    * Singleton accessor method for positionsOnly.
    */
   public static AllowedReportingType positionsOnly() {
      return _positionsOnly;
   }

   /**
    * Singleton accessor method for measurementsOnly.
    */
   public static AllowedReportingType measurementsOnly() {
      return _measurementsOnly;
   }

   /**
    * Singleton accessor method for positionsAndMeasurements.
    */
   public static AllowedReportingType positionsAndMeasurements() {
      return _positionsAndMeasurements;
   }

   /** Undefined value. */
   protected static AllowedReportingType __undefined_() { return __undefined; }

   public static final Decoder DECODER = new Decoder();

   public static class Decoder implements Asn1PerDecoder{

      public Asn1Type decode(Asn1PerDecodeBuffer buffer) throws Asn1Exception, java.io.IOException
      {
         return AllowedReportingType.valueOf( AllowedReportingType.decodeEnumValue( buffer ) );
      }
   }

   /**
    * Returns the instance associated with the value passed.
    * If the value passed is invalid, an exception is thrown.
    */
   public static AllowedReportingType valueOf (int _value)
   {
      switch ((int)_value) {
         case 0: return positionsOnly();
         case 1: return measurementsOnly();
         case 2: return positionsAndMeasurements();
         default: return __undefined_();
      }
   }

   public static int decodeEnumValue (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      int ui;  // enum index
      int ret; // return value
      boolean extbit = buffer.decodeBit ("extbit");

      if (extbit) {
         ui = buffer.decodeSmallNonNegWholeNumber ();

         return 0x7fffffff;
      }
      else {
         ui = (int) buffer.decodeConsWholeNumber (3);

         switch (ui) {
            case 0: ret =  0; break;
            case 1: ret =  1; break;
            case 2: ret =  2; break;
            default: throw new Asn1InvalidEnumException (ui);
         }
      }

      buffer.setTypeCode (Asn1Type.ENUMERATED);
      return ret;
   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      int ui;  // enum index
      boolean extbit = false;

      switch ((int)value) {
         case 0: ui = 0; /* positionsOnly */break;
         case 1: ui = 1; /* measurementsOnly */break;
         case 2: ui = 2; /* positionsAndMeasurements */break;
         default:
            ui = (int) value;
            extbit = true;
      }

      buffer.encodeBit (extbit, "extbit");

      if (extbit) {
         buffer.encodeSmallNonNegWholeNumber (ui);
      }
      else {
         buffer.encodeConsWholeNumber (ui, 3);
      }
   }

}
