/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.supl.ULP_Version_2_message_extensions;

import com.objsys.asn1j.runtime.*;
import org.mobicents.gmlc.slee.supl.SUPL_START.SETCapabilities;
import org.mobicents.gmlc.slee.supl.Ver2_ULP_Components.Ver2_HighAccuracyPosition;

public class Ver2_SUPL_END_extension extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_ULP_Version_2_message_extensionsRtkey._rtkey);
      Asn1Type._setLicLocation(_ULP_Version_2_message_extensionsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "Ver2-SUPL-END-extension";
   }

   protected SETCapabilities sETCapabilities;  // optional
   protected Ver2_HighAccuracyPosition ver2_HighAccuracyPosition;  // optional
   protected Asn1OpenExt extElem1;

   public Ver2_SUPL_END_extension () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public Ver2_SUPL_END_extension (
      SETCapabilities sETCapabilities_,
      Ver2_HighAccuracyPosition ver2_HighAccuracyPosition_
   ) {
      super();
      setSETCapabilities (sETCapabilities_);
      setVer2_HighAccuracyPosition (ver2_HighAccuracyPosition_);
   }

   public void init () {
      sETCapabilities = null;
      ver2_HighAccuracyPosition = null;
      extElem1 = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof Ver2_SUPL_END_extension) ) return false;

      Ver2_SUPL_END_extension rhs = (Ver2_SUPL_END_extension) obj;

      if (sETCapabilities == null) {
         if (rhs.sETCapabilities != null) return false;
      }
      else {
         if (!sETCapabilities.equals(rhs.sETCapabilities)) {
            return false;
         }
      }

      if (ver2_HighAccuracyPosition == null) {
         if (rhs.ver2_HighAccuracyPosition != null) return false;
      }
      else {
         if (!ver2_HighAccuracyPosition.equals(rhs.ver2_HighAccuracyPosition)) {
            return false;
         }
      }

      if (extElem1 == null) {
         if (rhs.extElem1 != null) return false;
      }
      else {
         if (!extElem1.equals(rhs.extElem1)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (sETCapabilities != null) __code = 31*__code + sETCapabilities.hashCode();
      if (ver2_HighAccuracyPosition != null) __code = 31*__code + ver2_HighAccuracyPosition.hashCode();
      if (extElem1 != null) __code = 31*__code + extElem1.hashCode();

      return __code;
   }

   /**
    * Accessor/mutator methods for SETCapabilities
    */
   public SETCapabilities getSETCapabilities () {
      return sETCapabilities;
   }

   public void setSETCapabilities (SETCapabilities value) {
      this.sETCapabilities = value;
   }

   public boolean hasSETCapabilities () {
      return (sETCapabilities != null);
   }

   /**
    * Accessor/mutator methods for Ver2_HighAccuracyPosition
    */
   public Ver2_HighAccuracyPosition getVer2_HighAccuracyPosition () {
      return ver2_HighAccuracyPosition;
   }

   public void setVer2_HighAccuracyPosition (Ver2_HighAccuracyPosition value) {
      this.ver2_HighAccuracyPosition = value;
   }

   public boolean hasVer2_HighAccuracyPosition () {
      return (ver2_HighAccuracyPosition != null);
   }

   /**
    * Accessor/mutator methods for ExtElem1
    */
   public Asn1OpenExt getExtElem1 () {
      return extElem1;
   }

   public void setExtElem1 (Asn1OpenExt value) {
      this.extElem1 = value;
   }

   public int getElementCount() { return 3; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return sETCapabilities;
         case 1: return ver2_HighAccuracyPosition;
         case 2: return extElem1;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "sETCapabilities";
         case 1: return "ver2-HighAccuracyPosition";
         case 2: return null;
         default: return null;
      }
   }


   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      init ();

      // extension bit

      boolean extbit = buffer.decodeBit ("extbit");

      // optional bits

      boolean sETCapabilitiesPresent = buffer.decodeBit ("sETCapabilitiesPresent");

      // decode sETCapabilities

      if (sETCapabilitiesPresent) {
         buffer.getContext().eventDispatcher.startElement("sETCapabilities", -1);

         sETCapabilities = new SETCapabilities();
         sETCapabilities.decode (buffer);
         buffer.getContext().eventDispatcher.endElement("sETCapabilities", -1);
      }
      else {
         sETCapabilities = null;
      }

      if (extbit) {

         int bitcnt = buffer.decodeSmallLength(), i = 0;
         long bitidx = buffer.getBitOffset() + bitcnt;
         boolean[] bitmap = new boolean [bitcnt];

         if (i < bitcnt) bitmap[i++] = buffer.decodeBit ("ver2_HighAccuracyPositionPresent");

         while (i < bitcnt) {
            bitmap[i++] = buffer.decodeBit ("unknown");
         }

         i = 0;

         // decode ver2_HighAccuracyPosition

         if (i < bitcnt && bitmap[i++]) {
            buffer.getContext().eventDispatcher.startElement("ver2_HighAccuracyPosition", -1);

            long _curidx = buffer.getBitOffset();
            bitidx = buffer.decodeExtLength ();
            if (bitidx - _curidx >= 131088)  {
               throw new Asn1Exception ("PER fragmentation not enabled: add -perindef to decode");
            }

            ver2_HighAccuracyPosition = new Ver2_HighAccuracyPosition();
            ver2_HighAccuracyPosition.decode (buffer);

            buffer.moveBitCursor (bitidx);
            buffer.getContext().eventDispatcher.endElement("ver2_HighAccuracyPosition", -1);

         }
         else {
            ver2_HighAccuracyPosition = null;
         }

         // decode unknown extension elements

         if (i < bitcnt) {
            Asn1OpenType openType = null;
            extElem1 = new Asn1OpenExt();
            int j = 0;
            while (i < bitcnt) {
               if (bitmap[i]) {
                  buffer.getContext().eventDispatcher.startElement("...", -1);

                  openType = extElem1.decodeOpenType (buffer, true, j++);
               }
               else {
                  extElem1.setOpenType (null, j++);
               }
               i++;
            }
         }
         buffer.byteAlign ();

      }

   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      // extension bit

      boolean extbit = ((ver2_HighAccuracyPosition != null) ||
      ((extElem1 != null) && (!extElem1.value.isEmpty()))
      );

      buffer.encodeBit (extbit, "extbit");

      // encode optional elements bit mask

      buffer.encodeBit ((sETCapabilities != null), null);

      // encode sETCapabilities

      if (sETCapabilities != null) {
         buffer.getContext().eventDispatcher.startElement("sETCapabilities", -1);

         sETCapabilities.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("sETCapabilities", -1);
      }

      if (extbit) {

         // encode extension optional bits length

         int bitcnt = 1;
         if (extElem1 != null) bitcnt += extElem1.value.size();
         buffer.encodeSmallLength (bitcnt);

         // encode optional bits

         buffer.encodeBit ((ver2_HighAccuracyPosition != null), null);

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encodeExtBits (buffer);
         }

         // encode extension elements

         Asn1PerEncodeBuffer mainBuffer = buffer;
         buffer = new Asn1PerEncodeBuffer (buffer.isAligned());

         // ver2_HighAccuracyPosition

         if (ver2_HighAccuracyPosition != null) {
            buffer.reset();
            ver2_HighAccuracyPosition.encode (buffer);
            buffer.getContext().eventDispatcher.startElement("ver2_HighAccuracyPosition", -1);

            mainBuffer.encodeOpenType (buffer, null);

            buffer.getContext().eventDispatcher.endElement("ver2_HighAccuracyPosition", -1);
         }

         buffer = mainBuffer;

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encode (buffer);
         }
      }
   }

}
