[[_dir_structure]]
== Directory Structure (JBoss AS)

When you download the binary release, you will notice that the top level directory is named `restcomm-gmlc-<version>` and immediately below this are five sub-directories as explained below:

* docs: Contains all relevant documentation in respective subfolders for JSLEE, jSS7, Management-HQ and GMLC.
* jboss-5.1.0.GA: The core server with two profiles "default" and "simulator". The "default" profile is a clean profile where you will have to start from scratch and configure the entire SS7 Stack and GMLC Gateway.
  The "simulator" profile is a pre-configured profile to work with jss7-simulator.
  Refer to the Admin Guide for instructions on how to start the server in either of the profiles.
* resources: Contains SLEE MAP, JDBC, http-client, http-servlet and SIP RA jars.
* tools: Contains SLEE tools and jss7-simulator.

----

|- restcomm-gmlc-<version>
		|- docs
				|+ jss7
				|+ slee
				|+ GMLC
				|+ management-hq
		|- jboss-5.1.0.GA
				|+ bin    //contains start up and shutdown scripts for the Server and the start up script for Shell.
				|+ client
				|+ common
				|+ docs
				|+ lib
				|- server
					|+ default	//clean profile to set up from scratch
					|+ simulator	//pre-configured profile to work with the jss7-simulator
		|- resources
				|+ http-client
				|+ map
		|- tools
				|+ eclipslee
				|+ jopr-plugin
				|+ remote-slee-connection
				|+ snmp
				|+ restcomm-jss7-simulator
				|+ twiddle
----