/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.supl.ULP_Components;

import com.objsys.asn1j.runtime.*;

public class FQDN extends Asn1VisibleString {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_ULP_ComponentsRtkey._rtkey);
      Asn1Type._setLicLocation(_ULP_ComponentsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "FQDN";
   }

   public final static Asn1CharSet CHARSET =
      new Asn1DiscreteCharSet ("-.0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");

   public FQDN () {
      super();
   }

   public FQDN (String value_) 
      throws Asn1Exception
   {
      super (value_);
      if (!((getLength() >= 1 && getLength() <= 255))) {
         throw new Asn1ConsVioException ("getLength()", getLength());
      }

   }

   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      super.decode (buffer, CHARSET, 1, 255);
   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      super.encode (buffer, CHARSET, 1, 255);
   }

}
