/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.supl.Ver2_ULP_Components;

import com.objsys.asn1j.runtime.*;

public class CellGlobalIdEUTRA extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_Ver2_ULP_ComponentsRtkey._rtkey);
      Asn1Type._setLicLocation(_Ver2_ULP_ComponentsRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "CellGlobalIdEUTRA";
   }

   protected PLMN_Identity plmn_Identity;
   protected CellIdentity cellIdentity;
   protected Asn1OpenExt extElem1;

   public CellGlobalIdEUTRA () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public CellGlobalIdEUTRA (
      PLMN_Identity plmn_Identity_,
      CellIdentity cellIdentity_
   ) throws Asn1Exception {
      super();
      setPlmn_Identity (plmn_Identity_);
      setCellIdentity (cellIdentity_);
   }

   public void init () {
      plmn_Identity = null;
      cellIdentity = null;
      extElem1 = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof CellGlobalIdEUTRA) ) return false;

      CellGlobalIdEUTRA rhs = (CellGlobalIdEUTRA) obj;

      if (plmn_Identity == null) {
         if (rhs.plmn_Identity != null) return false;
      }
      else {
         if (!plmn_Identity.equals(rhs.plmn_Identity)) {
            return false;
         }
      }

      if (cellIdentity == null) {
         if (rhs.cellIdentity != null) return false;
      }
      else {
         if (!cellIdentity.equals(rhs.cellIdentity)) {
            return false;
         }
      }

      if (extElem1 == null) {
         if (rhs.extElem1 != null) return false;
      }
      else {
         if (!extElem1.equals(rhs.extElem1)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (plmn_Identity != null) __code = 31*__code + plmn_Identity.hashCode();
      if (cellIdentity != null) __code = 31*__code + cellIdentity.hashCode();
      if (extElem1 != null) __code = 31*__code + extElem1.hashCode();

      return __code;
   }

   /**
    * Accessor/mutator methods for Plmn_Identity
    */
   public PLMN_Identity getPlmn_Identity () {
      return plmn_Identity;
   }

   public void setPlmn_Identity (PLMN_Identity value) {
      this.plmn_Identity = value;
   }

   /**
    * Accessor/mutator methods for CellIdentity
    */
   public CellIdentity getCellIdentity () {
      return cellIdentity;
   }

   public void setCellIdentity (CellIdentity value) 
      throws Asn1Exception
   {
      if (!(value.getLength() == 28)) {
         throw new Asn1ConsVioException ("value.getLength()", value.getLength());
      }

      this.cellIdentity = value;
   }

   /**
    * Accessor/mutator methods for ExtElem1
    */
   public Asn1OpenExt getExtElem1 () {
      return extElem1;
   }

   public void setExtElem1 (Asn1OpenExt value) {
      this.extElem1 = value;
   }

   public int getElementCount() { return 3; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return plmn_Identity;
         case 1: return cellIdentity;
         case 2: return extElem1;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "plmn-Identity";
         case 1: return "cellIdentity";
         case 2: return null;
         default: return null;
      }
   }


   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      init ();

      // extension bit

      boolean extbit = buffer.decodeBit ("extbit");

      // decode plmn_Identity

      buffer.getContext().eventDispatcher.startElement("plmn_Identity", -1);

      plmn_Identity = new PLMN_Identity();
      plmn_Identity.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("plmn_Identity", -1);

      // decode cellIdentity

      buffer.getContext().eventDispatcher.startElement("cellIdentity", -1);

      cellIdentity = new CellIdentity();
      cellIdentity.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("cellIdentity", -1);

      if (extbit) {

         int bitcnt = buffer.decodeSmallLength(), i = 0;
         long bitidx = buffer.getBitOffset() + bitcnt;
         boolean[] bitmap = new boolean [bitcnt];

         while (i < bitcnt) {
            bitmap[i++] = buffer.decodeBit ("unknown");
         }

         i = 0;

         // decode unknown extension elements

         if (i < bitcnt) {
            Asn1OpenType openType = null;
            extElem1 = new Asn1OpenExt();
            int j = 0;
            while (i < bitcnt) {
               if (bitmap[i]) {
                  buffer.getContext().eventDispatcher.startElement("...", -1);

                  openType = extElem1.decodeOpenType (buffer, true, j++);
               }
               else {
                  extElem1.setOpenType (null, j++);
               }
               i++;
            }
         }
         buffer.byteAlign ();

      }

   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      // extension bit

      boolean extbit = (((extElem1 != null) && (!extElem1.value.isEmpty()))
      );

      buffer.encodeBit (extbit, "extbit");

      // encode plmn_Identity

      if (plmn_Identity != null) {
         buffer.getContext().eventDispatcher.startElement("plmn_Identity", -1);

         plmn_Identity.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("plmn_Identity", -1);
      }
      else throw new Asn1MissingRequiredException ("plmn_Identity");

      // encode cellIdentity

      if (cellIdentity != null) {
         buffer.getContext().eventDispatcher.startElement("cellIdentity", -1);

         cellIdentity.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("cellIdentity", -1);
      }
      else throw new Asn1MissingRequiredException ("cellIdentity");

      if (extbit) {

         // encode extension optional bits length

         int bitcnt = 0;
         if (extElem1 != null) bitcnt += extElem1.value.size();
         buffer.encodeSmallLength (bitcnt);

         // encode optional bits

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encodeExtBits (buffer);
         }

         // encode extension elements

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encode (buffer);
         }
      }
   }

}
