/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.5.0, Date: 07-May-2021.
 */
package org.mobicents.gmlc.slee.supl.SUPL_NOTIFY;

import com.objsys.asn1j.runtime.*;
import org.mobicents.gmlc.slee.supl.SUPL_INIT.Notification;

public class Ver2_SUPLNOTIFY extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_SUPL_NOTIFYRtkey._rtkey);
      Asn1Type._setLicLocation(_SUPL_NOTIFYRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "Ver2-SUPLNOTIFY";
   }

   protected Notification notification;
   protected Asn1OpenExt extElem1;

   public Ver2_SUPLNOTIFY () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public Ver2_SUPLNOTIFY (
      Notification notification_
   ) {
      super();
      setNotification (notification_);
   }

   public void init () {
      notification = null;
      extElem1 = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof Ver2_SUPLNOTIFY) ) return false;

      Ver2_SUPLNOTIFY rhs = (Ver2_SUPLNOTIFY) obj;

      if (notification == null) {
         if (rhs.notification != null) return false;
      }
      else {
         if (!notification.equals(rhs.notification)) {
            return false;
         }
      }

      if (extElem1 == null) {
         if (rhs.extElem1 != null) return false;
      }
      else {
         if (!extElem1.equals(rhs.extElem1)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (notification != null) __code = 31*__code + notification.hashCode();
      if (extElem1 != null) __code = 31*__code + extElem1.hashCode();

      return __code;
   }

   /**
    * Accessor/mutator methods for Notification
    */
   public Notification getNotification () {
      return notification;
   }

   public void setNotification (Notification value) {
      this.notification = value;
   }

   /**
    * Accessor/mutator methods for ExtElem1
    */
   public Asn1OpenExt getExtElem1 () {
      return extElem1;
   }

   public void setExtElem1 (Asn1OpenExt value) {
      this.extElem1 = value;
   }

   public int getElementCount() { return 2; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return notification;
         case 1: return extElem1;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "notification";
         case 1: return null;
         default: return null;
      }
   }


   public void decode (Asn1PerDecodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      init ();

      // extension bit

      boolean extbit = buffer.decodeBit ("extbit");

      // decode notification

      buffer.getContext().eventDispatcher.startElement("notification", -1);

      notification = new Notification();
      notification.decode (buffer);
      buffer.getContext().eventDispatcher.endElement("notification", -1);

      if (extbit) {

         int bitcnt = buffer.decodeSmallLength(), i = 0;
         long bitidx = buffer.getBitOffset() + bitcnt;
         boolean[] bitmap = new boolean [bitcnt];

         while (i < bitcnt) {
            bitmap[i++] = buffer.decodeBit ("unknown");
         }

         i = 0;

         // decode unknown extension elements

         if (i < bitcnt) {
            Asn1OpenType openType = null;
            extElem1 = new Asn1OpenExt();
            int j = 0;
            while (i < bitcnt) {
               if (bitmap[i]) {
                  buffer.getContext().eventDispatcher.startElement("...", -1);

                  openType = extElem1.decodeOpenType (buffer, true, j++);
               }
               else {
                  extElem1.setOpenType (null, j++);
               }
               i++;
            }
         }
         buffer.byteAlign ();

      }

   }

   public void encode (Asn1PerEncodeBuffer buffer)
      throws Asn1Exception, java.io.IOException
   {
      // extension bit

      boolean extbit = (((extElem1 != null) && (!extElem1.value.isEmpty()))
      );

      buffer.encodeBit (extbit, "extbit");

      // encode notification

      if (notification != null) {
         buffer.getContext().eventDispatcher.startElement("notification", -1);

         notification.encode (buffer);

         buffer.getContext().eventDispatcher.endElement("notification", -1);
      }
      else throw new Asn1MissingRequiredException ("notification");

      if (extbit) {

         // encode extension optional bits length

         int bitcnt = 0;
         if (extElem1 != null) bitcnt += extElem1.value.size();
         buffer.encodeSmallLength (bitcnt);

         // encode optional bits

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encodeExtBits (buffer);
         }

         // encode extension elements

         if (extElem1 != null && extElem1.value.size() > 0) {
            extElem1.encode (buffer);
         }
      }
   }

}
