//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 10:01:58 PM EST 
//


package org.mobicents.gmlc.slee.mlp.v3_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}id"/>
 *         &lt;element ref="{}pwd" minOccurs="0"/>
 *         &lt;element ref="{}serviceid" minOccurs="0"/>
 *         &lt;element ref="{}requestmode" minOccurs="0"/>
 *         &lt;element ref="{}applicationid" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "pwd",
    "serviceid",
    "requestmode",
    "applicationid",
    "lcs_client_type",
    "lcs_client_name",
    "lcs_client_name_fi",
    "lcs_client_external_id",
    "lcs_client_internal_id",
    "lcs_service_type_id"
})
@XmlRootElement(name = "client")
public class Client {

    @XmlElement(required = true)
    protected String id;
    protected String pwd;
    protected String serviceid;
    protected Requestmode requestmode;
    protected Applicationid applicationid;
    // The following parameters are a customization for MAP PSL and Diameter SLg PLR
    protected String lcs_client_type;
    protected String lcs_client_name;
    protected String lcs_client_name_fi;
    protected String lcs_client_external_id;
    protected String lcs_client_internal_id;
    protected String lcs_service_type_id;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the pwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * Sets the value of the pwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwd(String value) {
        this.pwd = value;
    }

    /**
     * Gets the value of the serviceid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceid() {
        return serviceid;
    }

    /**
     * Sets the value of the serviceid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceid(String value) {
        this.serviceid = value;
    }

    /**
     * Gets the value of the requestmode property.
     * 
     * @return
     *     possible object is
     *     {@link Requestmode }
     *     
     */
    public Requestmode getRequestmode() {
        return requestmode;
    }

    /**
     * Sets the value of the requestmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Requestmode }
     *     
     */
    public void setRequestmode(Requestmode value) {
        this.requestmode = value;
    }

    /**
     * Gets the value of the applicationid property.
     * 
     * @return
     *     possible object is
     *     {@link Applicationid }
     *     
     */
    public Applicationid getApplicationid() {
        return applicationid;
    }

    /**
     * Sets the value of the applicationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Applicationid }
     *     
     */
    public void setApplicationid(Applicationid value) {
        this.applicationid = value;
    }

    /********************************/
    /*** Custom Getters & Setters ***/
    /********************************/

    public String getLcsClientType() {
        return lcs_client_type;
    }

    public void setLcsClientType(String value) {
        this.lcs_client_type = value;
    }

    public String getLcsClientName() {
        return lcs_client_name;
    }

    public void setLcsClientName(String value) {
        this.lcs_client_name = value;
    }

    public String getLcsClientNameFormatIndicator() {
        return lcs_client_name_fi;
    }

    public void setLcsClientNameFormatIndicator(String value) {
        this.lcs_client_name_fi = value;
    }

    public String getLcsClientExternalId() {
        return lcs_client_external_id;
    }

    public void setLcsClientExternalId(String value) {
        this.lcs_client_external_id = value;
    }

    public String getLcsClientInternalId() {
        return lcs_client_internal_id;
    }

    public void setLcsClientInternalId(String value) {
        this.lcs_client_internal_id = value;
    }

    public String getLcsServiceTypeId() {
        return lcs_service_type_id;
    }

    public void setLcsServiceTypeId(String value) {
        this.lcs_service_type_id = value;
    }
}
