//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 10:01:58 PM EST 
//


package org.mobicents.gmlc.slee.mlp.v3_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}hdr"/>
 *         &lt;choice>
 *           &lt;element ref="{}slir"/>
 *           &lt;element ref="{}eme_lir"/>
 *           &lt;element ref="{}tlrr"/>
 *           &lt;element ref="{}tlrsr"/>
 *           &lt;element ref="{}hlir"/>
 *           &lt;element ref="{}tlrqr"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="ver" default="3.4.0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="3.4.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hdr",
    "slir",
    "emeLir",
    "tlrr",
    "tlrsr",
    "hlir",
    "tlrqr"
})
@XmlRootElement(name = "svc_init")
public class SvcInit {

    @XmlElement(required = true)
    protected Hdr hdr;
    protected Slir slir;
    @XmlElement(name = "eme_lir")
    protected EmeLir emeLir;
    protected Tlrr tlrr;
    protected Tlrsr tlrsr;
    protected Hlir hlir;
    protected Tlrqr tlrqr;
    @XmlAttribute(name = "ver")
    protected String ver;

    /**
     * Gets the value of the hdr property.
     * 
     * @return
     *     possible object is
     *     {@link Hdr }
     *     
     */
    public Hdr getHdr() {
        return hdr;
    }

    /**
     * Sets the value of the hdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hdr }
     *     
     */
    public void setHdr(Hdr value) {
        this.hdr = value;
    }

    /**
     * Gets the value of the slir property.
     * 
     * @return
     *     possible object is
     *     {@link Slir }
     *     
     */
    public Slir getSlir() {
        return slir;
    }

    /**
     * Sets the value of the slir property.
     * 
     * @param value
     *     allowed object is
     *     {@link Slir }
     *     
     */
    public void setSlir(Slir value) {
        this.slir = value;
    }

    /**
     * Gets the value of the emeLir property.
     * 
     * @return
     *     possible object is
     *     {@link EmeLir }
     *     
     */
    public EmeLir getEmeLir() {
        return emeLir;
    }

    /**
     * Sets the value of the emeLir property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmeLir }
     *     
     */
    public void setEmeLir(EmeLir value) {
        this.emeLir = value;
    }

    /**
     * Gets the value of the tlrr property.
     * 
     * @return
     *     possible object is
     *     {@link Tlrr }
     *     
     */
    public Tlrr getTlrr() {
        return tlrr;
    }

    /**
     * Sets the value of the tlrr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tlrr }
     *     
     */
    public void setTlrr(Tlrr value) {
        this.tlrr = value;
    }

    /**
     * Gets the value of the tlrsr property.
     * 
     * @return
     *     possible object is
     *     {@link Tlrsr }
     *     
     */
    public Tlrsr getTlrsr() {
        return tlrsr;
    }

    /**
     * Sets the value of the tlrsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tlrsr }
     *     
     */
    public void setTlrsr(Tlrsr value) {
        this.tlrsr = value;
    }

    /**
     * Gets the value of the hlir property.
     * 
     * @return
     *     possible object is
     *     {@link Hlir }
     *     
     */
    public Hlir getHlir() {
        return hlir;
    }

    /**
     * Sets the value of the hlir property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hlir }
     *     
     */
    public void setHlir(Hlir value) {
        this.hlir = value;
    }

    /**
     * Gets the value of the tlrqr property.
     * 
     * @return
     *     possible object is
     *     {@link Tlrqr }
     *     
     */
    public Tlrqr getTlrqr() {
        return tlrqr;
    }

    /**
     * Sets the value of the tlrqr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tlrqr }
     *     
     */
    public void setTlrqr(Tlrqr value) {
        this.tlrqr = value;
    }

    /**
     * Gets the value of the ver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVer() {
        if (ver == null) {
            return "3.4.0";
        } else {
            return ver;
        }
    }

    /**
     * Sets the value of the ver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVer(String value) {
        this.ver = value;
    }

}
